// hov_speeches.js
// Banishment ceremony speech templates for "House of Villains"

window.hov_speeches = {
  // Generic speeches any nominee can use
winner: {
  good: [
"{A} stands tall and says they didn’t just play the game — they twerked on its grave and rebuilt it in rhinestones.",
"{A} claims they deserve the win because chaos is a skill set, and they majored in it with honors.",
"{A} reminds the jury that every villain needs an origin story, and they’re about to become the franchise.",
"{A} announces that if strategy were an art form, they’d be hanging in a museum labeled ‘Do Not Touch.’",
"{A} promises that crowning them means crowning the most entertaining disaster the house has ever seen.",
"{A} says the only thing bigger than their messy gameplay was the ratings spike they personally caused.",
"{A} insists they played the game like a villain and lived it like a meme — and that’s iconic behavior.",
"{A} declares that they didn’t burn bridges, they built runways, and now it’s time to take off.",
"{A} tells the jury that loyalty is cute, but strategic backstabbing is couture — and they wore it well.",
"{A} says if the show needs a face for future seasons, it should be theirs, because they're already shaped like a logo."
  ],
  neutral: [
"{A} shrugs and explains they did their best, even if their best sometimes involved crying behind cabinets.",
"{A} says they made some moves, missed some moves, and accidentally caused a fire once metaphorically.",
"{A} claims they tried their hardest to bond with everyone but also forgot half the house’s names twice.",
"{A} admits they were messy, but only like, medium-messy — the kind you can sweep up with a small broom.",
"{A} says they were loyal when they could be and dramatic when they couldn’t, which feels fair.",
"{A} explains they weren’t the worst finalist, which statistically makes them at least decent.",
"{A} tells the jury they learned, they grew, and they still don’t know what half the twists meant.",
"{A} says they didn’t strategize much, but they felt strategic, and feelings matter.",
"{A} insists their gameplay was like a slow burn, except sometimes nothing burned.",
"{A} says they gave the season heart, even if nobody asked for it."
],
bad: [
"{A} blames the jury for everything that went wrong and says voting for them is the least they could do.",
"{A} tells the jury they didn’t come here to make friends, and frankly, they didn’t — and that’s on them.",
"{A} says if they don’t win, they’re flipping every mattress in the house on general principle.",
"{A} threatens to leak everyone’s confessionals unless they vote correctly.",
"{A} says they didn’t play a good game, but neither did the jury, so everyone should calm down.",
"{A} reminds the jury they were targeted because they’re “just too fabulous,” which is obviously their fault.",
"{A} says they never respected the jury anyway but would appreciate the vote out of pity.",
"{A} claims they deserve to win because they survived sheerly by accident and dumb luck.",
"{A} tells the jury they should vote for them because “the other finalist smells weird.”",
"{A} says they’ve already written their winner’s speech, so it would be really embarrassing if they lost."
]},
elimination: {
good: [
"{A} says they are the drama glue holding this house together and without them the chaos budget will collapse",
"{A} tells everyone that keeping them is the only smart choice because they cause good TV and slightly less property damage than usual",
"{A} says they haven’t finished their villain arc yet so eliminating them now would be narratively irresponsible",
"{A} promises to stop stirring trouble for at least twenty minutes if everyone keeps them in the game",
"{A} claims the house needs their brand of unhinged leadership more than it needs peace and quiet",
"{A} says they can offer loyalty, alliance, and occasional emotional support if the lighting is flattering",
"{A} argues that voting them out would be like canceling a show before the good plot twist hits",
"{A} insists they still have more chaos to unleash but only in fun and legally harmless ways",
"{A} swears they will keep the house entertained and slightly off balance at all times",
"{A} promises to never target anyone who doesn't target them first which is practically diplomacy for this house",
"{A} says that without them the season would be about as exciting as a blank notepad",
"{A} claims they bring balance to the chaos because without them everyone else would start behaving normally",
"{A} offers snacks, gossip, and mild loyalty if granted one more episode of survival",
"{A} says they’re the only one willing to antagonize production when necessary for dramatic enhancement",
"{A} tells everyone they deserve to stay because their confessional lighting has finally started looking good",
"{A} asks the house to consider how boring the house meetings would be without their commentary",
"{A} declares themselves the emotional support villain everyone needs but refuses to admit they rely on",
"{A} says keeping them means guaranteed entertainment and fewer awkward silences",
"{A} promises to keep drama levels at a fun simmer instead of a dangerous boil",
"{A} reminds everyone they're the only one who actually knows how to fix the coffee machine",
"{A} says eliminating them now would rob the audience of too much unfulfilled potential villainy",
"{A} insists the season needs their unpredictable energy to maintain structural integrity",
"{A} vows to cause drama strategically instead of randomly which is personal growth for them",
"{A} explains that keeping them is the morally ambiguous but narratively correct choice",
"{A} says they will publicly support anyone here as long as they can privately talk trash later",
"{A} promises to weaponize their chaos only against people who deserve it or are boring",
"{A} claims they bring spice to every situation even when the situation didn’t need spice",
"{A} argues that if they leave the house vibe will shift from messy to mildly stable and nobody wants that",
"{A} promises to start using their powers for good villainy instead of chaotic villainy",
"{A} says they have several storylines left unresolved and eliminating them now is bad writing",
"{A} insists their elimination would break the prophecy they made up ten minutes ago",
"{A} offers to take accountability for all past drama which is huge for them",
"{A} says they will no longer throw people under the bus unless the bus is metaphorical",
"{A} promises to keep the house fed with both literal and figurative tea",
"{A} claims the house needs their delusion levels to stay properly calibrated",
"{A} says they bring the drama but also the vibe checks and the fashion",
"{A} argues that they are the comedic relief the season desperately needs",
"{A} insists the show’s editors would riot if they got eliminated now",
"{A} pleads dramatically but stylishly for one more week of villainy",
"{A} promises to be loyal to whoever keeps them even if loyalty is not their specialty",
"{A} says they came here to cause problems on purpose and they’re not done yet",
"{A} insists that keeping them is the strategic version of embracing chaos",
"{A} promises to only start fights that are narratively satisfying",
"{A} says the universe told them they’re meant to stay and who is anyone to argue with that",
"{A} reminds everyone they cause drama but never boring drama",
"{A} says they are the plot twist waiting to happen",
"{A} offers alliances, deals, and mild emotional support",
"{A} claims to be the only one truly committed to villain excellence",
"{A} promises to create unforgettable moments if given another chance",
"{A} says eliminating them now is simply bad television and everyone knows it"
],
neutral: [
"{A} says they should stay because they haven’t finished reorganizing their closet yet",
"{A} explains they deserve one more chance but isn’t sure why and hopes the house will fill in the blanks",
"{A} says they feel like staying would just be like convenient for them personally",
"{A} shrugs and says they guess they’re asking everyone for kindness even though it’s House of Villains",
"{A} promises to maybe try harder or at least pretend to",
"{A} says they haven’t annoyed anyone on purpose so that counts for something",
"{A} explains they could be a good ally if someone tells them how",
"{A} admits they don’t have a speech prepared but hopes for sympathy votes",
"{A} says they’re not ready to leave because their laundry isn’t done yet",
"{A} awkwardly claims they bring “like, vibes” and hopes that’s enough",
"{A} promises to be chill but can’t guarantee anything past noon tomorrow",
"{A} says they need to stay because they have unfinished business with the snack cabinet",
"{A} insists they haven’t been messy enough to warrant eviction yet",
"{A} says they’ll try to contribute more but might forget",
"{A} claims they are neutral chaos and therefore harmless",
"{A} says the house needs variety and they count as variety",
"{A} admits their strategy hasn’t started yet but insists it will",
"{A} awkwardly says they like everyone here even though they don't",
"{A} says they want to stay just to see what happens next",
"{A} makes vague promises about loyalty with zero specifics",
"{A} says they’re too tired to leave tonight",
"{A} insists they should stay because they haven't cried on camera yet",
"{A} claims they still need more footage for their highlight reel",
"{A} says they would be an easy number for anyone who wants one",
"{A} makes an alliance offer that’s basically just vibes",
"{A} says they bring “ambient chaos” but nothing dangerous",
"{A} promises nothing but asks for everything",
"{A} points out they haven’t been the worst person this week",
"{A} says they haven’t finished their dramatic house entrance arc",
"{A} argues that leaving now feels anticlimactic",
"{A} says they will try to be less confusing moving forward",
"{A} claims they still have potential even if no one sees it yet",
"{A} tells everyone they can at least guarantee entertainment value, probably",
"{A} says they are here to grow as a villain even though they haven't started growing",
"{A} says they have more confessionals to film before they’re eliminated",
"{A} promises to be chaotic in moderation",
"{A} shrugs and says they’re just hoping for grace",
"{A} says they don’t want to pack right now",
"{A} explains they’re emotionally unprepared to leave",
"{A} claims their presence adds texture to the show",
"{A} asks if they can have one more chance to disappoint people less",
"{A} promises to stop starting accidental drama",
"{A} admits they've been messy but not malicious",
"{A} suggests everyone think carefully but not too carefully",
"{A} says they’re just hoping for mercy at this point",
"{A} promises to contribute more but is visibly unsure how",
"{A} insists they can still be useful though they don't explain why",
"{A} says keeping them is the path of least resistance",
"{A} says their elimination would be inconvenient for their schedule",
"{A} ends by saying they hope for kindness even though it’s unlikely"
],
bad: [
"{A} threatens to haunt everyone’s confessionals if they get eliminated",
"{A} tells the house they are too iconic to be voted out and everyone else is filler",
"{A} says whoever votes them out is clearly threatened by their beauty and villain power",
"{A} insults half the room before asking them to save them",
"{A} claims the house would collapse without their drama but in a rude way",
"{A} announces that if they go down they’re taking at least three people with them socially",
"{A} says they will personally sabotage the season if they’re voted out",
"{A} claims they deserve to stay because everyone else is irrelevant",
"{A} tells the house they aren’t scared to expose every secret the moment they're eliminated",
"{A} accuses the room of being jealous of their villain aura",
"{A} blames everyone else for their own mistakes and expects sympathy",
"{A} calls the entire cast incompetent and demands to stay anyway",
"{A} says voting them out would be the dumbest decision since the invention of socks with sandals",
"{A} vows to emotionally destroy whoever writes their name down",
"{A} claims they are the main character and everyone else is background noise",
"{A} says they will poison the vibes of the house forever if eliminated",
"{A} tells the group that without them the show would be canceled instantly",
"{A} declares that they’re the star and everyone else is replaceable",
"{A} says they will refuse to leave even if they’re eliminated",
"{A} threatens to throw a tantrum on national television if voted out",
"{A} claims everyone should keep them because they said so",
"{A} tells the house they’re making a mistake because they’re not smart enough to play properly",
"{A} threatens to expose alliances mid-speech for attention",
"{A} says they’ve been carrying the season and everyone else is dead weight",
"{A} promises revenge but in a cheerful, unsettling way",
"{A} demands to stay because they haven't caused enough chaos yet",
"{A} openly threatens to flip every mattress in the house",
"{A} tells someone specific they will regret crossing them deeply",
"{A} claims they are the only real villain and everyone else is cosplay",
"{A} blames the entire house for being boring and says they need them to fix it",
"{A} says they don't need alliances because they’re better than alliances",
"{A} claims they’ll expose every lie they've ever told if eliminated",
"{A} says they will personally sabotage the final challenge out of spite",
"{A} states they are above the rules and should be saved automatically",
"{A} says they will scream until production intervenes if voted out",
"{A} threatens to hide all the hair products in retaliation",
"{A} promises to become everyone's worst nightmare if this vote goes wrong",
"{A} tells the house they're making history’s dumbest decision",
"{A} reminds everyone they know where people sleep",
"{A} vows to spread chaos in the group chat after elimination",
"{A} says if they go down they want the house to burn with them metaphorically",
"{A} claims the universe will punish whoever votes them out",
"{A} threatens to throw their mic pack into the pool again",
"{A} says they will ruin every meal for the rest of the season if eliminated",
"{A} aggressively tells the house to “do the right thing” without explaining what that means",
"{A} announces that anyone voting them out is dead to them socially and spiritually",
"{A} calls the entire house cowards for even considering eliminating them",
"{A} says they came here to be evil and they’re not done yet so too bad",
"{A} ends the speech by laughing maniacally in a way that concerns everyone"
]}
};
