// hov_events.js
// House events / drama templates for "House of Villains"

window.hov_events = {
  // One villain involved
  solo_neutral: [
"{A} spends ten minutes posing dramatically in the mirror for no reason",
"{A} forgets what they were about to say mid-sentence and walks away",
"{A} reheats coffee three times before actually drinking it",
"{A} tries to practice their villain laugh but accidentally snorts",
"{A} opens the fridge, forgets why, and closes it again",
"{A} walks into a room, says ‘mood shift,’ and leaves immediately",
"{A} dramatically storms toward the confessional but trips on nothing",
"{A} has a full conversation with themselves in the mirror",
"{A} spends twenty minutes rearranging pillows for the perfect aesthetic",
"{A} stares blankly at a wall while mentally planning nothing at all",
"{A} attempts to film a dramatic confessional but forgets to hit record",
"{A} tries to eavesdrop on people but can’t find a good hiding spot",
"{A} burns toast and blames the toaster for being ‘disrespectful’",
"{A} complains about chaos while actively causing most of it",
"{A} attempts meditation but falls asleep instantly",
"{A} talks to a houseplant as if it were an alliance member",
"{A} spends way too long choosing which sunglasses to wear indoors",
"{A} gets lost in the house despite living there for weeks",
"{A} opens a mystery drawer, closes it, and refuses to elaborate",
"{A} dramatically gasps at their own reflection thinking it was someone else",
"{A} starts practicing facial expressions for elimination night",
"{A} rehearses a comeback line but never gets to use it",
"{A} leaves a room to avoid drama but comes back when it sounds interesting",
"{A} tries to make a sandwich but forgets half the ingredients",
"{A} gets startled by their own shadow in the hallway",
"{A} spends an hour looking for their phone while holding it",
"{A} waves at a camera that isn’t filming",
"{A} narrates their own actions like they’re on a documentary",
"{A} strikes a villain pose every time someone walks by",
"{A} tries to summon drama but nothing happens",
"{A} puts on sunglasses indoors to feel ‘mysterious’",
"{A} asks the producer for a plot twist but gets denied",
"{A} sets up a dramatic moment but forgets the lines",
"{A} tries to open a locked door that isn’t actually locked",
"{A} eats a snack dramatically as if it’s a tense scene",
"{A} forgets their mic is on and sings terribly",
"{A} accidentally naps through an entire house argument",
"{A} practices slow-motion running for no reason",
"{A} overreacts to a tiny bug and then pretends they didn’t",
"{A} misinterprets a creak in the house as a sign of betrayal",
"{A} dramatically whispers to themselves even when alone",
"{A} tries to make a dramatic exit but walks the wrong direction",
"{A} sits in the dark to ‘set the mood’ but gets bored",
"{A} signals a camera like they’re in a spy movie",
"{A} accidentally gives themselves a pep talk in public",
"{A} rewrites their own backstory three times in one day",
"{A} leaves a confessional early thinking they nailed it but didn’t",
"{A} becomes convinced the house is sending them secret messages through décor",
"{A} dramatically rips open a snack bag and spills it everywhere"
  ],

  solo_positive: [
"{A} delivers a dramatic monologue in the mirror and actually nails it",
"{A} does a victory strut down the hallway for no reason and everyone applauds ironically",
"{A} makes a confession so unhinged that the producers start laughing off-camera",
"{A} discovers a secret camera angle that makes them look amazing and refuses to use any other",
"{A} gives themselves a fake villain nickname and it unexpectedly sticks",
"{A} steals the spotlight during a challenge purely by posing dramatically",
"{A} wins an argument purely through chaotic charisma and excessive hand gestures",
"{A} invents a catchphrase and accidentally makes it the house’s new greeting",
"{A} performs a petty celebration dance that becomes house lore",
"{A} convinces themselves they’re the main character and honestly everyone kind of supports it",
"{A} hosts a dramatic house meeting even though it wasn’t necessary at all",
"{A} takes a completely staged slow-motion walk that somehow looks iconic",
"{A} dramatically flips their hair and it lands perfectly like a movie scene",
"{A} cooks a chaotic breakfast and it shockingly tastes amazing",
"{A} wears an outfit so villain-coded that producers give them extra camera time",
"{A} purposely storms off but looks fabulous doing it",
"{A} starts a fake feud just for fun and everyone plays along",
"{A} improvises a dramatic speech and accidentally inspires the whole house",
"{A} gives a shady wink to the camera that becomes an instant meme",
"{A} narrates their day like a soap opera villain and it somehow works"
],
  solo_negative: [
"{A} accidentally spills their entire iced coffee down the stairs and blames gravity like it’s personal",
"{A} tries to make a dramatic entrance but trips on their own cape",
"{A} attempts a villainous laugh but starts coughing mid-cackle",
"{A} storms out of a room but forgets something and awkwardly has to come back",
"{A} burns instant ramen and makes the whole house question their survival skills",
"{A} gets caught practicing a dramatic speech to the mirror and pretends it was “performance art”",
"{A} tries to slam a door but it bounces back open",
"{A} spills glitter everywhere and spends an hour trying—failing—to clean it up",
"{A} gives a threatening stare but accidentally winks instead",
"{A} drops their snack right after announcing they “deserve nice things”",
"{A} dramatically flips their hair but gets it stuck in a plant",
"{A} tries to stalk through the hallway like a villain but squeaks loudly with every step",
"{A} makes a shady comment but immediately forgets who it was about",
"{A} attempts to flip a table but it’s too heavy and barely moves",
"{A} eats someone else's leftovers, panics, and tries to recreate the meal poorly",
"{A} tries to take a seductive slow-motion walk but walks into a doorframe",
"{A} attempts to eavesdrop but sneezes loudly from the dust",
"{A} dramatically throws their drink only to miss the trash can by a mile",
"{A} tries to intimidate someone and accidentally knocks over three chairs",
"{A} attempts to record a confession but realizes the camera wasn’t on the whole time"
],
  // Two villains involved
  two_neutral: [
"{A} and {B} accidentally show up to breakfast wearing the exact same villainous outfit",
"{A} and {B} get stuck in a revolving door together for an uncomfortable amount of time",
"{A} and {B} spend 20 minutes arguing about who ate the last slice of pizza, only to realize nobody ordered pizza",
"{A} and {B} try to secretly spy on each other but end up spying on the wrong people entirely",
"{A} and {B} get into a debate over whether a hot dog counts as a sandwich",
"{A} and {B} attempt to cook together but end up burning cereal",
"{A} and {B} form a temporary truce to catch a cockroach in the living room",
"{A} and {B} accidentally lock themselves outside and have to shout for help",
"{A} and {B} both try to prank the same person at the same time and ruin each other’s plan",
"{A} and {B} argue over whose fake tan is more ‘professionally villain-coded’",
"{A} and {B} try to film a dramatic confessional but talk over each other the whole time",
"{A} and {B} spend an hour trying to figure out a clue that wasn’t actually a clue",
"{A} and {B} accidentally pick the same bedsheets and have a petty debate about who bought them first",
"{A} and {B} both get scared by the same plant moving in the wind",
"{A} and {B} try to choreograph a villainous entrance walk but can’t agree on the music",
"{A} and {B} claim the house is haunted and spend the night investigating nothing",
"{A} and {B} attempt to do yoga together but keep falling onto each other",
"{A} and {B} can’t stop giggling during a serious house meeting",
"{A} and {B} accidentally swap water bottles and don’t notice for hours",
"{A} and {B} attempt to recreate a meme but forget what the meme was halfway through",
"{A} and {B} get stuck in a loop of saying ‘no, you go first’ at a doorway",
"{A} and {B} discover a hidden room but it’s just a storage closet",
"{A} and {B} try to whisper a secret plan but everyone nearby hears everything",
"{A} and {B} attempt to playfully insult each other but keep complimenting by accident",
"{A} and {B} start a fake feud over who took the last energy drink",
"{A} and {B} start a house-wide scavenger hunt for an item {A} had in their pocket the whole time",
"{A} and {B} try to practice their villain laughs together and confuse the entire house",
"{A} and {B} decide to have a silent staring contest that lasts an absurdly long time",
"{A} and {B} accidentally walk into each other’s confessionals mid-rant",
"{A} and {B} get distracted mid-conversation and forget what they were fighting about",
"{A} and {B} attempt to read tarot cards but mix up the instructions",
"{A} and {B} spend 10 minutes trying to open a door that wasn’t even locked",
"{A} and {B} argue whether the moon looks ‘evil’ enough for their vibe tonight",
"{A} and {B} both claim ownership of the house remote but don’t actually want to choose what to watch",
"{A} and {B} accidentally create matching villain catchphrases",
"{A} and {B} try to be intimidating but slip on the same rug",
"{A} and {B} attempt to form a secret alliance in a room with a live microphone",
"{A} and {B} bond over their mutual confusion during a challenge",
"{A} and {B} race to the kitchen for snacks and end up sharing a bag of chips",
"{A} and {B} forget why they walked into a room and leave without solving the mystery",
"{A} and {B} reenact a dramatic soap opera scene for fun",
"{A} and {B} attempt to solve a puzzle together but overcomplicate it drastically",
"{A} and {B} start a fake argument just to confuse everyone else",
"{A} and {B} both try to be the ‘mysterious villain’ but keep ruining their own entrances",
"{A} and {B} have a dramatic face-off that ends with both laughing",
"{A} and {B} try to make dramatic tea but overheat the water and set the alarm off",
"{A} and {B} share a moment of mutual confusion reading the challenge instructions",
"{A} and {B} negotiate who gets the last gummy worm in the candy jar",
"{A} and {B} accidentally start a rumor about themselves and have to clear it up",
"{A} and {B} try to scare each other and end up scaring themselves instead"
  ],
  two_positive: [
"{A} and {B} hype each other up before a challenge like they're rehearsing for a villain-themed TED Talk",
"{A} and {B} make matching evil-queen smoothies and toast to ‘chaotic excellence’",
"{A} and {B} do a slow-motion villain strut down the hallway together for no reason",
"{A} and {B} team up to prank the house but end up laughing too hard to finish it",
"{A} and {B} spend an hour doing face masks while plotting imaginary revenge arcs",
"{A} and {B} create a secret handshake that has way too many steps",
"{A} and {B} defend each other at a house meeting like dramatic soap-opera lawyers",
"{A} and {B} duet a villainous laugh until everyone else leaves the room",
"{A} and {B} accidentally invent a catchphrase the whole house starts using",
"{A} and {B} hype each other up in the mirror like overdramatic cheer captains",
"{A} and {B} choreograph a dramatic entrance for the elimination ceremony",
"{A} and {B} scream when they see a spider and then compliment each other’s bravery",
"{A} and {B} have a heartfelt midnight talk about their villain origin stories",
"{A} and {B} share snacks during a fight because ‘even villains need fuel’",
"{A} and {B} roast the entire cast together in the pantry like it’s a podcast",
"{A} and {B} reenact a dramatic movie scene just to entertain themselves",
"{A} and {B} gas each other up so hard that the house thinks they formed a cult",
"{A} and {B} accidentally start a conga line during a house party",
"{A} and {B} help each other pick outfits like fashion-obsessed supervillains",
"{A} and {B} make friendship bracelets that say ‘evil besties’",
"{A} and {B} celebrate winning a challenge by dancing terribly on purpose",
"{A} and {B} gossip in whispers that are somehow still loud enough for everyone to hear",
"{A} and {B} decide to call themselves ‘The Final Two’ on day one",
"{A} and {B} team up to redecorate a bedroom into a ‘villain lair’",
"{A} and {B} laugh so hard at a joke that the cameras shake",
"{A} and {B} host a fake awards show for most dramatic house moments",
"{A} and {B} rehearse dramatic exit speeches they never have to use",
"{A} and {B} cheer when the other wins something like it’s the Olympics",
"{A} and {B} start harmonizing during confessional interviews",
"{A} and {B} accidentally start talking in villain voices for the rest of the day",
"{A} and {B} recreate their favorite reality TV fight scenes with dramatic flair",
"{A} and {B} plan their imaginary spin-off show together",
"{A} and {B} high-five after surviving a house argument they weren’t even involved in",
"{A} and {B} hold hands dramatically walking into elimination like it’s a finale",
"{A} and {B} scream compliments at each other from across the house",
"{A} and {B} share a donut and call it ‘a symbol of our chaotic bond’",
"{A} and {B} pretend to be detectives solving a mystery that doesn’t exist",
"{A} and {B} defend each other’s honor over the stupidest misunderstandings",
"{A} and {B} film fake confessionals hyping each other up as masterminds",
"{A} and {B} make a dramatic pact to never betray each other ‘unless it’s funny’",
"{A} and {B} help each other cheat during a board game like cartoon villains",
"{A} and {B} laugh at inside jokes no one else understands",
"{A} and {B} try to meditate together but end up giggling the whole time",
"{A} and {B} coordinate their outfits like they’re walking a villain fashion runway",
"{A} and {B} comfort each other after a bad day with dramatic speeches",
"{A} and {B} hype each other up so much that producers have to tell them to calm down",
"{A} and {B} take villain selfies with over-the-top facial expressions",
"{A} and {B} make a list of ‘overdramatic goals’ for the week",
"{A} and {B} bond over how much they love causing mild chaos",
"{A} and {B} accidentally start crying laughing during a serious strategy talk"
  ],
  two_negative: [
"{A} throws shade at {B} for no reason, calling them a 'discount villain' behind their back.",
"{A} steals {B}'s skincare routine and then denies it on camera.",
"{A} mocks {B}'s villain laugh, calling it 'Dollar Store diabolical.'",
"{A} flips out after {B} eats their labeled leftovers.",
"{A} loudly accuses {B} of having 'main character syndrome' in front of everyone.",
"{A} sabotages {B}'s outfit by hiding their shoes before elimination night.",
"{A} makes a fake alliance with {B} and exposes it thirty minutes later.",
"{A} tells everyone {B} cried in the bathroom—even though they didn’t.",
"{A} rolls their eyes dramatically whenever {B} speaks during house meetings.",
"{A} blames {B} for the house running out of wine.",
"{A} tells {B} their villain persona is 'giving children’s birthday clown.'",
"{A} pretends not to hear {B}'s name during roll call.",
"{A} spreads a rumor that {B} sleeps with a night-light shaped like a raccoon.",
"{A} steals {B}'s bed and replaces it with a bean bag.",
"{A} mocks {B}'s signature catchphrase until {B} storms off.",
"{A} tells the house {B} is the reason the hot tub smells weird.",
"{A} ruins {B}'s dramatic confessional by screaming through the walls.",
"{A} fake cries to make {B} look heartless in front of the group.",
"{A} laughs when {B}'s dramatic exit gets ruined by a stuck door.",
"{A} calls out {B} for wearing 'the same outfit in three episodes.'",
"{A} makes snarky comments about {B}'s villain strategy being 'Pinterest-inspired.'",
"{A} accuses {B} of hiding the remote when {A} lost it.",
"{A} gives {B} a sarcastic slow clap after every sentence they say.",
"{A} switches {B}’s shampoo with glitter gel.",
"{A} stirs the pot by telling {B} that everyone found their prank 'mid.'",
"{A} mocks {B}'s attempt at an evil monologue.",
"{A} accuses {B} of reheating fish in the microwave, causing chaos.",
"{A} threatens to expose {B}'s secret alliance to the entire house.",
"{A} loudly tells production they want {B} evicted for 'crimes against fashion.'",
"{A} purposely mispronounces {B}'s name during arguments.",
"{A} starts a fight after {B} calls their villain persona 'budget couture.'",
"{A} throws {B}'s pillow off the balcony during a meltdown.",
"{A} posts a fake apology note pretending to be {B}.",
"{A} accuses {B} of stealing their mascara—even though {A} doesn't wear any.",
"{A} votes against {B} in a challenge and celebrates too hard afterward.",
"{A} laughs at {B}'s dramatic walk-in entrance replaying on the TV.",
"{A} hides {B}'s sunglasses just before a dramatic confrontation.",
"{A} says {B} gives 'sidekick energy' during group arguments.",
"{A} exposes {B}'s secret snack stash to the whole house.",
"{A} throws a villain tantrum because {B} got more camera time.",
"{A} fakes an injury and blames {B} for 'emotional sabotage.'",
"{A} ruins {B}'s big villain speech by coughing loudly the entire time.",
"{A} tells {B} nobody remembers their introduction episode.",
"{A} accuses {B} of plotting even when {B} is literally napping.",
"{A} interrupts {B}'s confessional to yell, 'LIES!'",
"{A} tells the house {B} can’t be trusted because 'their eyebrows look sneaky.'",
"{A} switches {B}'s coffee to decaf and watches chaos unfold.",
"{A} fake whispers to make {B} paranoid all day.",
"{A} purposely turns off the lights when {B} is in the shower.",
"{A} starts clapping sarcastically every time {B} walks into a room."
  ],

  // Three villains involved
  three_neutral: [
"{A}, {B}, and {C} form a temporary ‘evil trio’ but dissolve it five minutes later over snack preferences",
"{A}, {B}, and {C} try to sneak through the house but get caught immediately by a camera operator",
"{A}, {B}, and {C} rehearse a dramatic slow-motion group entrance but forget to coordinate",
"{A}, {B}, and {C} attempt to start a secret meeting but loudly argue over where to sit",
"{A}, {B}, and {C} get stuck in a revolving door and blame each other for it",
"{A}, {B}, and {C} form a conga line during a house fight to ‘lighten the mood’",
"{A}, {B}, and {C} decide to prank the house but accidentally prank themselves instead",
"{A}, {B}, and {C} host a villain fashion show in the hallway with improvised outfits",
"{A}, {B}, and {C} try to make a TikTok dance but get every step wrong",
"{A}, {B}, and {C} attempt to form an alliance but immediately forget the terms",
"{A}, {B}, and {C} stage a dramatic fake betrayal scene for the cameras",
"{A}, {B}, and {C} compete to see who can do the most dramatic sigh",
"{A}, {B}, and {C} try to cook dinner together and set off the fire alarm",
"{A}, {B}, and {C} accidentally start a house rumor about a fourth contestant",
"{A}, {B}, and {C} spend an hour arguing over what the challenge twist could be",
"{A}, {B}, and {C} recreate a famous movie scene for absolutely no reason",
"{A}, {B}, and {C} debate who has the better villain laugh and never settle it",
"{A}, {B}, and {C} try to meditate together but burst out laughing",
"{A}, {B}, and {C} host a mock elimination ceremony complete with fake torches",
"{A}, {B}, and {C} attempt to map out alliances on a whiteboard but get confused",
"{A}, {B}, and {C} make a secret handshake that’s ten steps too long",
"{A}, {B}, and {C} critique everyone’s outfits while eating popcorn in the corner",
"{A}, {B}, and {C} join forces to fix a broken lamp and break it even more",
"{A}, {B}, and {C} spend an hour searching for a clue that never existed",
"{A}, {B}, and {C} try to choreograph a group entrance and fall out of sync instantly",
"{A}, {B}, and {C} practice intimidation poses but keep hyping each other up instead",
"{A}, {B}, and {C} sneak snacks into a room and call it a ‘summit meeting’",
"{A}, {B}, and {C} attempt to host a talk show and argue about who gets the spotlight",
"{A}, {B}, and {C} get into a fight about which of them is the ‘main villain’ of the season",
"{A}, {B}, and {C} dramatically vow loyalty to each other before immediately plotting separate plans"
],
   three_positive: [
"{A}, {B}, and {C} accidentally form an alliance while bonding over how bad the house coffee is",
"{A}, {B}, and {C} stay up late plotting world domination but mostly end up laughing about nothing",
"{A}, {B}, and {C} hype each other up with villain monologues in the mirror until they’re crying laughing",
"{A}, {B}, and {C} flawlessly coordinate matching outfits and intimidate the entire house",
"{A}, {B}, and {C} recreate a dramatic movie scene together and somehow make it even campier",
"{A}, {B}, and {C} join forces to fix the WiFi and celebrate like they won a challenge",
"{A}, {B}, and {C} accidentally choreograph a synchronized evil laugh that makes everyone else nervous",
"{A}, {B}, and {C} share snacks, secrets, and slander in the pantry like a true villain trio",
"{A}, {B}, and {C} team up to prank the whole house and celebrate with a group villain pose",
"{A}, {B}, and {C} combine their brain cells to solve a clue and somehow actually succeed",
"{A}, {B}, and {C} form a dramatic blood-oath alliance over a spilled energy drink",
"{A}, {B}, and {C} coordinate confessionals to gaslight the house in the funniest way possible",
"{A}, {B}, and {C} create a fake prophecy about themselves becoming the Final Three",
"{A}, {B}, and {C} team up to deep-clean the kitchen and instantly become everyone’s favorite trio",
"{A}, {B}, and {C} declare themselves the Chaos Committee and promise to stir the pot together",
"{A}, {B}, and {C} hype each other up before a challenge with a campy motivational chant",
"{A}, {B}, and {C} unlock a perfectly petty trio dynamic that scares their rivals",
"{A}, {B}, and {C} start a three-way handshake so complicated nobody else is allowed to join",
"{A}, {B}, and {C} bond over making fun of a challenge twist they all misunderstood",
"{A}, {B}, and {C} accidentally invent a trend in the house and take full credit together",
"{A}, {B}, and {C} decide to be each other’s alibis after a prank gets out of control",
"{A}, {B}, and {C} realize they gossip best as a trio and make it an official alliance rule",
"{A}, {B}, and {C} spend an hour laughing about something that wasn’t even funny",
"{A}, {B}, and {C} practice their villain struts together and scare someone walking by",
"{A}, {B}, and {C} host a fake press conference about why they deserve immunity as a trio"
],
   three_negative: [
"{A}, {B} and {C} try to form a secret alliance but immediately start accusing each other of lying",
"{A}, {B} and {C} attempt a group confessional but end up screaming over each other",
"{A}, {B} and {C} start a ‘trust circle’ that collapses within 30 seconds",
"{A}, {B} and {C} get into a fight over who gets credit for a plan that didn’t even work",
"{A}, {B} and {C} make a pact but {A} rats out the other two before they leave the room",
"{A}, {B} and {C} attempt a choreographed villain walk and immediately trip over one another",
"{A}, {B} and {C} try to sabotage someone but accidentally sabotage each other instead",
"{A}, {B} and {C} argue over which one of them is the ‘real mastermind’ until security gets called",
"{A}, {B} and {C} start a fight in the kitchen that ends with all of them banning each other from snacks",
"{A}, {B} and {C} playfully roast each other until it stops being playful",
"{A}, {B} and {C} attempt to hide evidence of a prank but expose themselves instantly",
"{A}, {B} and {C} call a house meeting but forget why and end up fighting anyway",
"{A}, {B} and {C} try to vote together but end up splitting the vote out of pure spite",
"{A}, {B} and {C} get into a screaming match about who controls the alliance group chat",
"{A}, {B} and {C} start an alliance only for {C} to immediately betray both for dramatic effect",
"{A}, {B} and {C} attempt a group makeup session that ends with all their products destroyed",
"{A}, {B} and {C} practice villain laughs together until someone gets offended at a comparison",
"{A}, {B} and {C} accuse each other of stealing the same hoodie",
"{A}, {B} and {C} try to rehearse call-out speeches but insult each other in the process",
"{A}, {B} and {C} confront each other about loyalty and end up confessing three totally different lies",
"{A}, {B} and {C} attempt to start drama with someone else but accidentally turn on each other",
"{A}, {B} and {C} get into a petty argument about who is the real fan favorite",
"{A}, {B} and {C} stage a dramatic walkout but no one follows them",
"{A}, {B} and {C} attempt to share tea but end up spilling everyone’s secrets including their own",
"{A}, {B} and {C} try to hold hands for unity but immediately start arguing about sweaty palms",
"{A}, {B} and {C} ruin an alliance meeting by talking trash about each other’s villain personas",
"{A}, {B} and {C} form a voting bloc only to discover none of them voted the same way",
"{A}, {B} and {C} attempt a confrontation but forget who they were supposed to confront",
"{A}, {B} and {C} fight over mirror time and break the mirror in the process",
"{A}, {B} and {C} try to practice intimidation poses and insult each other's posture",
"{A}, {B} and {C} accuse each other of creating fake screenshots of text messages",
"{A}, {B} and {C} start a prank war that destroys half the house decor",
"{A}, {B} and {C} try to film a TikTok together but fight over who stands in the center",
"{A}, {B} and {C} attempt to eavesdrop but argue too loudly while hiding",
"{A}, {B} and {C} host a secret meeting in the pantry and accidentally lock themselves inside",
"{A}, {B} and {C} fight over a single hairbrush for 45 minutes",
"{A}, {B} and {C} clash about who should do the dramatic toast at dinner",
"{A}, {B} and {C} ruin each other's strategy notes while arguing about pen colors",
"{A}, {B} and {C} try to build trust by sharing secrets only to immediately weaponize them",
"{A}, {B} and {C} attempt a peace talk but end up ranking each other’s villain monologues",
"{A}, {B} and {C} get into a petty rivalry over whose laugh is ‘more iconic’",
"{A}, {B} and {C} attempt synchronized villain poses but keep insulting each other’s angles",
"{A}, {B} and {C} start a petty war over who hogged the ring light",
"{A}, {B} and {C} try to plan a blindside but forget who they’re voting out",
"{A}, {B} and {C} end up in a three-way shouting match over a misunderstanding none of them explains",
"{A}, {B} and {C} break into tears mid-argument but still keep arguing",
"{A}, {B} and {C} fight over who gets the last villain-themed cocktail",
"{A}, {B} and {C} accidentally expose their alliance in front of everyone while screaming at each other",
"{A}, {B} and {C} attempt a dramatic group exit but can’t agree on who goes first",
"{A}, {B} and {C} start a rumor about someone else only to accidentally prove it false themselves"
]
};
