window.BOTS_EVENTS = {
  // ------------------------------------------------------
  // SOLO EVENTS
  // ------------------------------------------------------

  solo_neutral: [
    "{A} sips coffee alone on the patio, watching the sun come up.",
    "{A} hums to themselves while folding laundry in silence.",
    "{A} stares at the memory wall, lost in thought.",
    "{A} reorganizes the fridge just to keep busy.",
    "{A} flips through a magazine someone left behind.",
    "{A} waters the plants and whispers, 'you’re doing better than some people here.'",
    "{A} takes a nap in the lounge, half-listening to distant laughter.",
    "{A} writes imaginary headlines about house drama in their head.",
    "{A} lingers near the pool, overhearing a conversation not meant for them.",
    "{A} paces the hallway, debating whether to clear the air with someone.",
    "{A} cheers themself up by dancing in the mirror.",
    "{A} storms out of the kitchen muttering that everyone’s fake.",
    "{A} admits privately that they’re proud of how far they’ve come.",
    "{A} watches the group talk and smiles, quietly rooting for everyone.",
    "{A} calls themself 'the only real one left' under their breath.",
    "{A} rewrites a mental list of who’s 'dead to them' before dinner.",
    "{A} paces the hall rehearsing the perfect one-liner for their next blow-up.",
    "{A} mutters that people confuse kindness for weakness.",
    "{A} isolates themselves from everyone, hoodie up and headphones on.",
    "{A} tidies their corner of the bedroom without saying a word.",
    "{A} watches the living room chaos from the stairs, expression unreadable.",
    "{A} cooks a late-night snack while half the house naps.",
"{A} alphabetizes the spice rack even though half the labels are missing",
"{A} stares out the window pretending to be in a dramatic music video",
"{A} practices their villain laugh in the bathroom but stops when someone walks by",
"{A} reorganizes the couch pillows for the third time today",
"{A} quietly studies the cameras wondering which ones are actually on",
"{A} doodles tiny stick-figure contestants in the margin of a notebook",
"{A} sits by the pool dipping just one toe in for five full minutes",
"{A} flips a coin to decide whether to be petty today",
"{A} whispers a pep talk to themself before walking into the kitchen",
"{A} rewinds the security footage in their head trying to remember who said what",
"{A} wanders the house looking for snacks but finds only protein bars",
"{A} scrolls through old mental memories like they’re Instagram posts",
"{A} sits in the dark living room because they don’t feel like turning on the lights",
"{A} slow-blinks at the camera like they’re in a sitcom",
"{A} rearranges their bed pillows into a throne for no reason",
"{A} stands in front of the fridge with the door open contemplating life",
"{A} hums the show’s theme song under their breath while microwaving leftovers",
"{A} silently judges everyone’s water bottle hygiene",
"{A} gives themself a pep talk in the mirror about being 'mysterious and unfazed'",
"{A} eats a snack on the stairs like it’s their secret hideout",
"{A} tries to meditate but gets distracted by their own thoughts",
"{A} watches a bug crawl across the floor and decides it’s not their problem",
"{A} wraps themself in a blanket like a dramatic burrito",
"{A} stares at the challenge schedule on the wall like it personally offended them",
"{A} talks to the fish tank for emotional support",
"{A} reads the rulebook again just to make sure they're not secretly breaking anything",
"{A} leans dramatically against a doorway like a soap opera character",
"{A} sends themselves to 'time out' on the patio chair after getting annoyed",
"{A} side-eyes the pantry as if it wronged them",
"{A} whispers 'I knew it' to absolutely no one",
"{A} laughs at a joke they remembered from three days ago",
"{A} stands in the hallway pretending they forgot why they're there",
"{A} takes a dramatic sip of water like it's a confessional moment",
"{A} carefully picks lint off their shirt like it’s a full-time job",
"{A} sits on the floor sorting through random house cards and game tokens",
"{A} dramatically flips their hair even though no one is watching",
"{A} uses a fork as a microphone for an imaginary acceptance speech",
"{A} sits cross-legged on the counter like it’s perfectly normal behavior",
"{A} quietly arranges the shoes lined up by the door",
"{A} whispers 'plot twist' when nothing is happening",
"{A} reviews their own imaginary social game strategy",
"{A} counts ceiling tiles to pass the time",
"{A} reenacts an argument with perfect facial expressions",
"{A} practices their shocked reaction faces for future drama",
"{A} tries to predict who will fight next just for fun",
"{A} naps with sunglasses on indoors",
"{A} checks their reflection in the microwave door",
"{A} yawns loudly hoping someone will notice but no one does"
  ],

  // ------------------------------------------------------
  // TWO-PERSON EVENTS
  // ------------------------------------------------------

  two_neutral: [
    "{A} and {B} chat casually about their hometowns.",
    "{A} and {B} sit by the pool comparing favorite snacks.",
    "{A} and {B} swap stories about awkward past relationships.",
    "{A} and {B} wash dishes together while humming an old song.",
    "{A} and {B} share a blanket on the couch while talking about family.",
    "{A} and {B} laugh about how messy the house has gotten.",
    "{A} and {B} talk about what life will feel like after the show.",
    "{A} and {B} joke that they’ve both become neat freaks in here.",
    "{A} and {B} play a quick game of cards to pass time.",
    "{A} and {B} trade stories about their worst roommates ever.",
    "{A} and {B} compare who snores louder at night.",
    "{A} and {B} spend the afternoon doing absolutely nothing productive.",
    "{A} and {B} chat about food cravings they’ll indulge after filming.",
    "{A} and {B} laugh about inside jokes no one else understands.",
    "{A} and {B} talk through small misunderstandings and move on easily.",
    "{A} and {B} walk slow laps discussing how to avoid injury.",
    "{A} and {B} stretch back-to-back and nod in sync.",
    "{A} and {B} quietly observe who trains with who from the stairs.",
    "{A} and {B} split a protein snack and keep it moving.",
    "{A} and {B} do a light run through the courtyard.",
    "{A} and {B} spend the afternoon chatting in the lounge.",
    "{A} and {B} prepare a meal together in the kitchen.",
    "{A} and {B} accidentally wear matching outfits.",
    "{A} and {B} take turns using the bathroom mirror while getting ready.",
    "{A} and {B} discover they both like the same snack.",
    "{A} and {B} briefly discuss the day’s weather.",
    "{A} and {B} stand by the kitchen counter picking at leftover snacks.",
    "{A} and {B} lean on the balcony railing people-watching the rest of the house.",
    "{A} and {B} compare how badly they slept in the shared bedroom.",
    "{A} and {B} sit on the couch guessing what time it is.",
    "{A} and {B} quietly fold their clothes and talk about the day.",
    "{A} and {B} joke about how many cameras must be pointed at them right now.",
    "{A} and {B} clean up the dining table after everyone finishes eating.",
    "{A} and {B} stand at the fridge debating what leftovers to reheat.",
    "{A} and {B} rearrange their drawers and swap a couple of shelves.",
    "{A} and {B} sit on the stairs watching a game unfold in the yard.",
    "{A} and {B} count how many water bottles are scattered around the house.",
    "{A} and {B} practice tongue twisters and laugh when they mess up.",
    "{A} and {B} go through the chore list and divide tasks without fuss.",
    "{A} and {B} take turns sweeping the floor in the living room.",
    "{A} and {B} compare how long they usually take to get ready at home.",
    "{A} and {B} chat about the weirdest thing they’ve eaten in the house so far.",
    "{A} and {B} stretch in a corner of the yard, talking about sore muscles.",
    "{A} and {B} casually review who seems tired before the next challenge.",
    "{A} and {B} sit side by side on the couch, commenting quietly on the chaos.",
    "{A} and {B} walk slow laps around the yard to shake off nerves.",
    "{A} and {B} organize the bathroom counter and toss out empty containers.",
    "{A} and {B} stand by the sink brushing their teeth at the same time.",
    "{A} and {B} compare how much water they’ve been drinking in the house.",
    "{A} and {B} sit on the edge of the pool, dipping their feet in the water.",
    "{A} and {B} go over the basic rules they remember in a calm tone.",
    "{A} and {B} chat about which types of challenges they feel okay about.",
    "{A} and {B} sit at the dining table doodling patterns on scrap paper.",
    "{A} and {B} rearrange pillows on the couch while making small talk.",
    "{A} and {B} quietly watch the sunset from the yard.",
    "{A} and {B} talk about what kind of breakfast they hope to have tomorrow.",
    "{A} and {B} shuffle a deck of cards and agree on simple house rules.",
    "{A} and {B} play a quick card game while idly chatting.",
    "{A} and {B} lean against the wall in the hallway, whispering about nothing serious.",
    "{A} and {B} compare how many confessionals they’ve done so far.",
    "{A} and {B} sit cross-legged on the floor, talking about their daily routines at home.",
    "{A} and {B} fold blankets together and stack them neatly at the end of the couch.",
    "{A} and {B} pace around the living room to shake out nervous energy.",
    "{A} and {B} sit in the shade, talking about how strange the time feels here.",
    "{A} and {B} chat about which spots in the house feel most peaceful.",
    "{A} and {B} stand near the door, guessing when the next announcement will come."
  ],

  two_positive: [
    "{A} comforts {B} after a stressful day in the house.",
    "{A} compliments {B}’s outfit and they both laugh about fashion disasters.",
    "{A} shares a snack with {B} without being asked.",
    "{A} helps {B} calm down after an awkward group moment.",
    "{A} tells {B} that they’ve genuinely started to like them as a person.",
    "{A} and {B} stay up late talking about everything and nothing.",
    "{A} and {B} have a deep conversation about trust.",
    "{A} surprises {B} with coffee just the way they like it.",
    "{A} helps {B} fix a ripped shirt and jokes about being their stylist.",
    "{A} tells {B} they’ve got their back no matter what.",
    "{A} reassures {B} that the tension in the house isn’t all about them.",
    "{A} and {B} laugh until they cry over a silly misunderstanding.",
    "{A} checks in on {B} and says, 'you don’t have to fake it here.'",
    "{A} gives {B} the last clean towel because 'karma points matter.'",
    "{A} says they’d actually hang out with {B} in real life.",
    "{A} sticks up for {B} when others criticize them.",
    "{A} cheers {B} up with a funny impression.",
    "{A} supports {B} during a tense group meeting.",
    "{A} and {B} plan to look out for each other.",
    "{A} and {B} stay up late talking about their dreams.",
    "{A} reassures {B} they can trust them.",
    "{A} and {B} share a secret about someone else in the house.",
    "{A} tells {B} they’re one of the most genuine people here.",
    "{A} tells {B} they handled a tough moment better than most people would.",
    "{A} saves a seat for {B} at the table without saying anything.",
    "{A} pulls {B} aside just to ask if they’re really okay.",
    "{A} lets {B} vent about the house drama without interrupting.",
    "{A} tells {B} they’re proud of how they did in the last challenge.",
    "{A} and {B} share a quiet hug after a long, emotional day.",
    "{A} thanks {B} for being one of the few people they feel safe around.",
    "{A} tells {B} they’re glad they met them through this experience.",
    "{A} helps {B} organize their things when the room feels overwhelming.",
    "{A} tells {B} they’re stronger than they give themselves credit for.",
    "{A} and {B} sit in a corner hyping each other up before a challenge.",
    "{A} promises {B} they won’t repeat something that was said in confidence.",
    "{A} lets {B} take the better bed spot without making a big deal of it.",
    "{A} gives {B} a pep talk in the hallway before a tense conversation.",
    "{A} and {B} share a genuine laugh that cuts through the tension.",
    "{A} tells {B} they’re one of the few people they fully trust in the house.",
    "{A} trades chores with {B} so {B} can have a quieter afternoon.",
    "{A} openly credits {B} for helping them do well in a challenge.",
    "{A} quietly tells {B} they deserve to be here just as much as anyone.",
    "{A} backs up {B}’s version of events when the group starts to doubt them.",
    "{A} and {B} celebrate a small win together with a goofy handshake.",
    "{A} thanks {B} for not judging them when they were vulnerable.",
    "{A} tells {B} they appreciate how honest they’ve been in the game.",
    "{A} notices {B} is withdrawn and gently invites them to join the group.",
    "{A} tells {B} they’re one of the few real friendships they’ve made here.",
    "{A} and {B} talk about how they want to support each other after the show.",
    "{A} nudges {B} to speak up in a group talk and nods encouragingly.",
    "{A} quietly comforts {B} on the couch while everyone else argues.",
    "{A} offers to swap beds with {B} so they can sleep farther from the noise.",
    "{A} tells {B} that seeing them push through fear is inspiring.",
    "{A} and {B} share a quick high-five after surviving another elimination.",
    "{A} reassures {B} that one bad moment doesn’t define their character.",
    "{A} notices {B} is anxious and starts small talk to distract them.",
    "{A} tells {B} that they hope the two of them never have to face off.",
    "{A} openly thanks {B} in front of others for keeping things real.",
    "{A} sits with {B} in silence just so they don’t have to be alone.",
    "{A} reminds {B} of all the things they’ve already overcome in life.",
    "{A} and {B} agree that no matter what happens, they won’t trash each other.",
    "{A} offers {B} the more comfortable seat during a long house meeting.",
  ],

  two_negative: [
    "{A} accuses {B} of talking behind their back.",
    "{A} says {B} has no backbone and just follows the crowd.",
    "{A} calls {B} a 'walking press release' for whoever’s winning.",
    "{A} tells everyone {B} has been scheming since day one.",
    "{A} and {B} get into a shouting match about loyalty.",
    "{A} mocks {B}’s ‘nice-guy routine’ in front of half the house.",
    "{A} rolls their eyes every time {B} speaks until {B} finally snaps.",
    "{A} says {B} tries too hard to act calm when they’re clearly scared.",
    "{A} claims {B} leaked private conversations for clout.",
    "{A} tells {B} they’ll 'crumble under pressure anyway.'",
    "{A} says {B} doesn’t deserve to be here and refuses to explain why.",
    "{A} calls {B} the 'house mascot' in a tone that’s not friendly.",
    "{A} and {B} nearly come to blows before others intervene.",
    "{A} shouts that {B} only forms alliances out of fear.",
    "{A} loudly declares that {B}’s apology 'doesn’t come with receipts.'",
    "{A} starts a sarcastic slow clap when {B} walks in the room.",
    "{A} says {B} is a chameleon and it’s time people noticed.",
    "{A} calls {B} ‘a walking PR move’ and walks out mid-conversation.",
    "{A} tells the entire house that {B} flips sides whenever convenient.",
    "{A} drunkenly announces that {B} ‘couldn’t win an argument, let alone a final.’",
    "{A} gets tipsy and points at {B} across the room: ‘Say it with your chest, not your whisper.’",
    "{A} tells the entire house that {B} rehearses confessional lines in the mirror.",
    "{A} and {B} argue about who left the kitchen messy.",
    "{A} accuses {B} of spreading rumors.",
    "{A} ignores {B} during a group conversation.",
    "{A} takes {B}'s food from the fridge without asking.",
    "{A} and {B} argue over who should get the better bed.",
    "{A} interrupts {B} constantly during a discussion.",
    "{A} laughs at {B}'s mistake.",
    "{A} rolls their eyes at something {B} says.",
    "{A} tells others that {B} can’t be trusted.",
    "{A} refuses to help {B} clean up a shared mess.",
    "{A} criticizes {B}'s cooking.",
    "{A} accuses {B} of being lazy.",
    "{A} and {B} get into a heated argument over chores.",
    "{A} calls out {B} for being fake.",
    "{A} says {B} is only here for attention.",
    "{A} gets annoyed at {B}'s constant talking.",
    "{A} gossips about {B} to someone else.",
    "{A} and {B} argue over who’s more popular in the house.",
    "{A} moves {B}'s belongings without permission.",
    "{A} tells {B} they’re only brave in confessionals, not face-to-face.",
    "{A} snaps that {B} plays the victim every time they’re called out.",
    "{A} accuses {B} of throwing challenges to avoid getting blood on their hands.",
    "{A} says {B} only talks game when cameras are nearby.",
    "{A} tells {B} they’ve been riding coattails since day one.",
    "{A} complains that {B} changes their story every time someone new walks in.",
    "{A} corners {B} in the hallway and demands to know which side they’re on.",
    "{A} tells {B} they’re ‘doing too much for someone who’s done so little.’",
    "{A} claims {B} only acts friendly when they need a vote.",
    "{A} rolls their eyes and tells {B} to stop pretending to be neutral.",
    "{A} tells {B} their loyalty ‘expires every 24 hours.’",
    "{A} says {B} sounds like they’re auditioning instead of being honest.",
    "{A} mocks {B} for crying after stirring up tension in the house.",
    "{A} loudly says {B} is the last person they’d want to run a final with.",
    "{A} accuses {B} of repeating private talks to the wrong people.",
    "{A} tells {B} their apology feels like ‘damage control, not remorse.’",
    "{A} complains that {B} only shows up when it benefits their image.",
    "{A} calls {B} a flip-flopper and lists every side they’ve been on.",
    "{A} tells {B} they’re all talk and no action in challenges.",
    "{A} snipes that {B} wouldn’t survive one week without protection.",
    "{A} says {B} is ‘all strategy, no substance’ during a group argument.",
    "{A} accuses {B} of using kindness as a cover for manipulation.",
    "{A} tells {B} they disappear whenever it’s time to take responsibility.",
    "{A} bluntly tells {B} they’re only safe because others keep saving them.",
    "{A} scoffs that {B} thinks they’re running the game from the sidelines.",
    "{A} calls {B} out in front of everyone for giving two different promises.",
    "{A} tells {B} they only act confused to avoid picking a side.",
    "{A} says {B} is ‘all ears when gossip starts, never a voice when it matters.’",
    "{A} accuses {B} of trying to play both hero and victim at the same time.",
    "{A} mocks the way {B} suddenly becomes quiet when accountability comes up.",
    "{A} complains that {B} always shows up last when chores are assigned.",
    "{A} and {B} snap at each other over who left clothes all over the room.",
    "{A} moves {B}’s suitcase out of the way and says they’re taking up too much space.",
    "{A} mutters that {B} only cleans when people are watching.",
    "{A} accuses {B} of hogging the bathroom before every event.",
    "{A} grumbles that {B} never helps set up for group meals.",
    "{A} tells others that {B} is dead weight in both the house and the game.",
    "{A} rolls their eyes when {B} walks into the room and goes quiet on purpose.",
    "{A} and {B} argue over who twisted whose words during a previous conversation.",
    "{A} tells {B} they’re ‘only brave in groups, never one-on-one.’"
  ],

  // ------------------------------------------------------
  // THREE-PERSON EVENTS
  // ------------------------------------------------------

  team_neutral: [
    "{A}, {B}, and {C} cook dinner together while teasing each other.",
    "{A}, {B}, and {C} sit in the lounge telling embarrassing stories.",
    "{A}, {B}, and {C} debate who snores the loudest.",
    "{A}, {B}, and {C} laugh at {C}’s failed attempt to fix the coffee maker.",
    "{A}, {B}, and {C} chat about how weird it feels being on camera all the time.",
    "{A}, {B}, and {C} invent a fake talk show just to fill the silence.",
    "{A}, {B}, and {C} gossip lightly about who might be getting too confident.",
    "{A}, {B}, and {C} play a truth-or-dare game that spirals into laughter.",
    "{A}, {B}, and {C} talk about how much they miss real privacy.",
    "{A}, {B}, and {C} accidentally start a karaoke night with no music.",
    "{A}, {B}, and {C} discuss how unpredictable everyone’s moods have become.",
    "{A}, {B}, and {C} joke about who would survive best in the real world together.",
    "{A}, {B}, and {C} sit under blankets talking about nothing deep at all.",
    "{A}, {B}, and {C} speculate which pair secretly flirts when no one’s looking.",
    "{A}, {B}, and {C} laugh about how over-dramatic people get when bored.",
    "{A}, {B}, and {C} share snacks at the counter while chatting about the day.",
    "{A}, {B}, and {C} sit on the couch ranking past challenges from easiest to hardest.",
    "{A}, {B}, and {C} take turns guessing what time it is with no clocks around.",
    "{A}, {B}, and {C} wander around the yard pointing out the best napping spots.",
    "{A}, {B}, and {C} fold laundry together while trading light jokes.",
    "{A}, {B}, and {C} sit on the stairs quietly watching the rest of the house.",
    "{A}, {B}, and {C} rearrange pillows on the couch until it looks perfect to them.",
    "{A}, {B}, and {C} share random facts about themselves just to pass time.",
    "{A}, {B}, and {C} compare how long it usually takes them to get ready at home.",
    "{A}, {B}, and {C} talk about the strangest habits they’ve noticed in the house.",
    "{A}, {B}, and {C} sit at the dining table doodling patterns on scrap paper.",
    "{A}, {B}, and {C} pace small circles in the yard to shake off cabin fever.",
    "{A}, {B}, and {C} quietly organize the pantry and comment on everyone’s snack choices.",
    "{A}, {B}, and {C} lean over the balcony railing, people-watching the others.",
    "{A}, {B}, and {C} compare which rooms in the house feel the most awkward.",
    "{A}, {B}, and {C} share random childhood memories without going too deep.",
    "{A}, {B}, and {C} chat in the hallway about who seems the most competitive.",
    "{A}, {B}, and {C} stretch on the floor and talk about sore muscles.",
    "{A}, {B}, and {C} sit under blankets joking about how cold the house feels.",
    "{A}, {B}, and {C} walk slow laps around the living room mid-conversation.",
    "{A}, {B}, and {C} talk about what kind of breakfast they hope for tomorrow.",
    "{A}, {B}, and {C} compare their worst nights of sleep in the shared bedroom.",
    "{A}, {B}, and {C} sit on the floor near the beds, just casually talking.",
    "{A}, {B}, and {C} clean the kitchen together without really planning it.",
    "{A}, {B}, and {C} joke about how many times they’ve all forgotten the cameras.",
    "{A}, {B}, and {C} casually rank the quietest and loudest people in the house.",
    "{A}, {B}, and {C} sit in a circle listing small things they miss from home.",
    "{A}, {B}, and {C} talk about which kind of challenge they’d hate the most.",
    "{A}, {B}, and {C} sit against a wall in the hallway, chatting between events.",
    "{A}, {B}, and {C} tease each other about who hogs the bathroom longest.",
    "{A}, {B}, and {C} joke about how dramatic everyone gets when they’re bored.",
    "{A}, {B}, and {C} sit by the pool, feet in the water, talking about nothing specific.",
    "{A}, {B}, and {C} compare who uses the most pillows and blankets at night.",
    "{A}, {B}, and {C} speculate who will be the messiest once the game gets tougher.",
    "{A}, {B}, and {C} quietly observe a small argument from a distance and shrug it off.",
    "{A}, {B}, and {C} stand in the kitchen trying to estimate how many days are left.",
    "{A}, {B}, and {C} talk about what they think the next twist might be.",
    "{A}, {B}, and {C} sit in the shade, trading light comments about the house routine.",
    "{A}, {B}, and {C} compare who has the most stuff packed into their drawers."
  ],
};
