// =========================================
// ANTM — Panel notes (9 buckets)
// photoshootTier: good/mid/bad
// challengeTier:  good/mid/bad
// =========================================

window.ANTM_PANEL_NOTES = {
    good: {
      good: [
        "{A}, this was a complete domination. When you’re on, you’re dangerous.",
        "{A}, you took the concept and made it look like your own campaign. Flawless.",
        "The photo is breathtaking, {A}. This is the caliber of work that defines the competition.",
        "{A}, you understood the assignment on a deeper level. The result is editorial gold.",
        "{A}, you walked in, delivered the shot, and reminded everyone why you’re a front-runner.",
        "That’s a cover shot, {A}. You commanded the frame with intelligence and precision.",
        "We had high expectations, {A}, and you shattered them. A masterclass in execution.",
        "The subtlety in your expression, {A}, is what separates a good photo from a great one.",
        "You didn’t just pose, {A}, you performed. The photo tells a complete story.",
        "{A}, you were the photographer’s dream today. Every frame was a winner.",
        "Your confidence translated directly into the lens, {A}. This is world-class work.",
        "{A}, you made a difficult concept look effortless. That’s the mark of a true professional.",
        "The light loved you today, {A}, because you knew exactly how to work with it.",
        "{A}, you sold the fantasy. You made us believe in the world of the shoot completely.",
        "This is the shot we came here to get from you, {A}. Do not lose this momentum.",
        "Your face carried the entire narrative, {A}. A powerful, silent performance.",
        "{A}, you didn’t just wear the clothes; you gave them meaning and life.",
        "You were the clear standout in a strong group, {A}. The photo is iconic.",
        "Your instincts were perfect today, {A}. You trusted yourself and it shows.",
        "We saw a new level of maturity in your work this week, {A}. This is your next chapter.",
        "{A}, you worked the camera, not the other way around. That’s control.",
        "The composition hinges on your presence, {A}. You anchored the chaos beautifully.",
        "You brought a sophistication to this that we haven’t seen before, {A}. Keep it.",
        "{A}, you didn’t just hit the brief; you expanded it. That’s creativity.",
        "This photo has a point of view, {A}. It’s specific, memorable, and high-fashion.",
        "You took a risk and it paid off spectacularly, {A}. That’s how you make a statement.",
        "{A}, your connection with the environment was perfect. You belonged there.",
        "Every detail, from your fingertips to your gaze, was considered, {A}. Impeccable.",
        "You set the bar, {A}. This is the standard you need to maintain.",
        "{A}, you proved today that you can go toe-to-toe with anyone in this competition."
      ],
      mid: [
        "{A}, the photo is strong, but you left something on the table earlier in the week.",
        "The photo saves you, {A}, but the inconsistency is starting to become a pattern.",
        "You delivered where it counts most, {A}, but you cannot afford to coast on challenges.",
        "This picture is why you’re still here, {A}. Now match this energy in every task.",
        "A stunning recovery in photos, {A}. Let’s see that fire from the very beginning next week.",
        "The camera loves you, {A}, but the competition demands more than just a great picture.",
        "You’re a star in front of the lens, {A}, but the challenge showed a lack of fight.",
        "This photo proves your potential is limitless, {A}. Start acting like it all the time.",
        "{A}, your photo is head and shoulders above the rest, but your performance was middle of the pack.",
        "You have a switch, {A}, and it only seems to flip for the photoshoot. We need it on always.",
        "The end result is beautiful, {A}, but the journey to get there was shaky.",
        "You can clearly deliver magic, {A}. The question is why you waited until the last moment.",
        "This shot is portfolio-worthy, {A}. Your challenge performance was not.",
        "You separated yourself with this photo, {A}. Don’t let the other aspects hold you back.",
        "We see the champion in this frame, {A}. Now we need to see her in the challenge room.",
        "The photo is your safety net, {A}. Stop relying on it and start dominating every day.",
        "You have a gift for the still image, {A}. Your challenge work needs to catch up to it.",
        "This level of work in the photoshoot, {A}, should be your baseline, not your peak.",
        "You won the week with this photo, {A}, but you nearly lost it in the challenge.",
        "Your focus seems singular, {A}. Great for photos, dangerous for the rest of the competition.",
        "The photo is a ten, {A}. Your week was a seven. We need tens across the board.",
        "You can turn it on when it matters, {A}. Make every moment matter.",
        "This is the version of you we want to see permanently, {A}. Not just on shoot days.",
        "Your photo speaks for itself, {A}. Your challenge performance was silent.",
        "You have the raw talent, {A}, evident in this shot. The polish needs to be constant.",
        "A photo this good buys you time, {A}, but it doesn’t buy you the win.",
        "You’re playing with fire, {A}. This photo put it out, but the smoke is still there.",
        "The discrepancy is glaring, {A}. One moment you’re a master, the next you’re a student.",
        "This photo is your passport to next week, {A}. Your challenge effort almost cancelled the flight.",
        "You have an 'on' switch, {A}. It’s time to remove the switch and just be on."
      ],
      bad: [
        "{A}, your photo saved you — but you can’t keep ignoring the challenge side.",
        "This photo is the only reason you’re still standing here, {A}. That is not a strategy.",
        "You’re surviving on your pictures alone, {A}, and that lifeline is running out.",
        "The photo is a masterpiece, {A}. The rest of your week was a mess.",
        "You’re a puzzle, {A}. Brilliant in one piece, completely lost in the other.",
        "This shot is your get-out-of-jail-free card, {A}. You’re on your last one.",
        "The gap between your photoshoot and challenge performance is unacceptable, {A}.",
        "You’re treating this like two separate competitions, {A}. It’s one, and you’re failing half of it.",
        "The photo is your redeeming quality, {A}. You have nothing else to redeem right now.",
        "You’re wasting your own talent, {A}. This photo shows what you could be every day.",
        "We’re running out of patience, {A}. This photo buys you a week, not a future.",
        "You’re a ghost in the challenges, {A}, and a giant in photos. We need the whole person.",
        "This is a warning, {A}. Your photo work is exceptional. Everything else is a liability.",
        "You cannot photoshoot your way to the finale, {A}. The challenges will eliminate you.",
        "The photo is a band-aid, {A}. It’s covering a wound that needs real treatment.",
        "You’re giving us 50%, {A}. The photo is 100%, the challenge was 0%.",
        "This inconsistency is your biggest enemy, {A}. The photo defeated it this week.",
        "You’re lucky the photo was this strong, {A}, because the challenge was that weak.",
        "Stop resting on your laurels, {A}. This photo is a laurel. The challenge was a nap.",
        "You’re a part-time model in this competition, {A}. The photo is your full-time job.",
        "The judges shouldn’t have to debate your place here every week, {A}. This photo ended the debate, but you started it.",
        "You’re giving us whiplash, {A}. From forgettable to unforgettable, back and forth.",
        "This photo is your apology, {A}. We’re no longer accepting apologies.",
        "You’re on thin ice, {A}. This photo just thickened it slightly.",
        "Your potential is clear in this frame, {A}. Your execution everywhere else is not.",
        "The photo is your passport, {A}. Your challenge performance is a expired visa.",
        "You’re building a house on sand, {A}. The photo is a beautiful window, but the foundation is crumbling.",
        "We see two different people, {A}. We need the one from this photo to show up tomorrow.",
        "This photo is a reminder of what you *can* do, {A}. The challenge was a reminder of what you *didn’t* do.",
        "You’re a liability to yourself, {A}. This photo is your only asset right now."
      ]
    },
    mid: {
      good: [
        "{A}, you showed up in the challenge, but the photo didn’t translate. The camera needs more.",
        "Your challenge effort was strong, {A}, but the photo feels disconnected and safe.",
        "You fought hard this week, {A}, but the final image doesn’t reflect that battle.",
        "The energy was there in the room, {A}, but it got lost somewhere between the set and the print.",
        "You proved you’re a competitor in the challenge, {A}, but you didn’t prove you’re a model in the photo.",
        "We saw fire from you in the challenge, {A}, but the photo is a flicker.",
        "You understood the brief intellectually, {A}, but the photo lacks emotional conviction.",
        "Your performance was promising, {A}, but the photo is a letdown. The lens didn’t capture your fight.",
        "You worked hard, {A}, but the camera didn’t work for you. The connection wasn’t made.",
        "The challenge showed your versatility, {A}, but the photo shows a one-dimensional side.",
        "You were a team player and a leader, {A}, but in the photo, you’re just a participant.",
        "Your challenge work was sharp and focused, {A}, but the photo is blurry in its intention.",
        "We got to know you better this week, {A}, but the photo doesn’t add to that story.",
        "You took risks in the challenge, {A}, but played it painfully safe in the photoshoot.",
        "The spark was there, {A}, but it never ignited into a flame for the camera.",
        "You gave us personality all week, {A}, and then left it in the styling trailer.",
        "Your challenge showed growth, {A}, but the photo shows stagnation.",
        "You were memorable in the challenge, {A}, and forgettable in the photo.",
        "You earned your spot this week with your effort, {A}, but you didn’t earn a top spot with your photo.",
        "The challenge proved you belong here, {A}. The photo made us question why.",
        "You had momentum, {A}, and you let it stall completely in front of the lens.",
        "We saw a fighter, {A}, but the photo shows someone who’s already given up.",
        "Your voice was loud and clear all week, {A}, but in the photo, you’re silent.",
        "You built a great case for yourself, {A}, and then the photo was your weakest evidence.",
        "The challenge was your strength, {A}, and the photoshoot was your weakness this week.",
        "You were present and accounted for, {A}, until the moment the shutter clicked.",
        "You showed us a new side, {A}, and then hid it again for the main event.",
        "Your potential is obvious from your challenge work, {A}. Your photo made it theoretical.",
        "You did everything right except the most important thing, {A}.",
        "The challenge was your audition for the top, {A}. The photo was your callback for the middle."
      ],
      mid: [
        "{A}, it’s a safe week. Safe is not a strategy — it’s a warning.",
        "You’re floating in the middle, {A}, and that’s the most dangerous place to be.",
        "No major missteps, {A}, but no standout moments either. You’re wallpaper.",
        "You did enough to get by, {A}, and in this competition, 'enough' is not enough.",
        "You’re becoming predictable, {A}. We know exactly what we’ll get: adequacy.",
        "You’re neither here nor there, {A}. You’re just… present. That’s not enough.",
        "This was a placeholder week for you, {A}. You cannot afford placeholders.",
        "You’re on autopilot, {A}, and autopilot doesn’t win competitions.",
        "You’re not giving us a reason to send you home, {A}, but you’re not giving us a reason to keep you either.",
        "You’re treading water, {A}, and the sharks are circling.",
        "Mediocrity is a slow death in this competition, {A}. You’re flirting with it.",
        "You’re a ghost this week, {A}. We see you, but you leave no impression.",
        "You’re doing the work, {A}, but where’s the passion? Where’s the point of view?",
        "You’re checking boxes, {A}. We’re looking for someone who breaks them.",
        "You’re blending in, {A}, when you should be standing out.",
        "You’re playing not to lose, {A}. You need to play to win.",
        "There’s no signature, {A}. Your work is anonymous.",
        "You’re in the gray area, {A}, and this competition is won in black and white.",
        "You’re fading into the background, {A}. It’s time to step into the light or step out.",
        "You’re giving us the minimum, {A}. The minimum gets you eliminated.",
        "We’re forgetting you while you’re still here, {A}. That’s the biggest problem.",
        "You’re a passenger, {A}. It’s time to take the wheel.",
        "Your performance was 'fine,' {A}. 'Fine' is the enemy of 'fantastic.'",
        "You’re not making mistakes, {A}, but you’re not making memories either.",
        "You’re existing in this competition, {A}, not competing in it.",
        "You’re a question mark, {A}, and the answer is starting to look like 'no.'",
        "You’re waiting for something to happen, {A}. You need to make it happen.",
        "You’re coasting on pleasantness, {A}. This is not a popularity contest; it’s a model search.",
        "You’re giving us nothing to criticize, {A}, and nothing to celebrate.",
        "You’re the definition of middle of the pack, {A}. The pack is thinning."
      ],
      bad: [
        "{A}, you struggled across the board. We need to see growth, not panic.",
        "This was a bad week, {A}. The challenge was shaky, and the photo was lost.",
        "You’re regressing, {A}. The confidence we saw is gone, replaced by hesitation.",
        "You’re in your own head, {A}, and it’s showing in every single thing you do.",
        "The pressure is getting to you, {A}, and it’s eroding your talent.",
        "You’re not adapting, {A}. You’re trying to force a square peg into a round hole every time.",
        "You’re thinking too much, {A}, and feeling too little. The work is stiff and calculated.",
        "You’re making the same mistakes, {A}, and hoping for a different result.",
        "You’re your own worst enemy this week, {A}. The doubt is louder than your talent.",
        "You’re unraveling, {A}, and we can see every thread coming loose.",
        "The light is dimming in your eyes, {A}. You need to find the switch again, fast.",
        "You’re giving up before you even start, {A}. The defeat is written all over your face.",
        "You’re not listening, {A}. You’re hearing, but you’re not absorbing and applying.",
        "You’re fighting the process, {A}, instead of using it to elevate yourself.",
        "You’re a shadow of the model you were in week one, {A}. What happened?",
        "You’re lost, {A}, and it’s painfully obvious to everyone in this room.",
        "You’re not connecting, {A}. Not with the clients, not with the camera, not with us.",
        "The spark is gone, {A}. You’re going through the motions, and the motions are wrong.",
        "You’re overcomplicating everything, {A}. Simplicity and confidence are what you need.",
        "You’re trying to be someone else, {A}, and in the process, you’ve lost yourself.",
        "You’re in survival mode, {A}, and survival mode is not a winning strategy.",
        "You’re waiting for permission to be great, {A}. The permission is yours. Take it.",
        "You’re letting the competition happen to you, {A}. You need to happen to the competition.",
        "You’re stuck, {A}, and if you don’t get unstuck, you’re going home.",
        "You’re performing from a place of fear, {A}, not a place of power.",
        "You’re missing the point, {A}, over and over again.",
        "You’re not learning, {A}. You’re repeating. That’s a one-way ticket out.",
        "You’re shrinking when you should be expanding, {A}.",
        "You’ve hit a wall, {A}, and you’re just standing there looking at it.",
        "This week was a step backward, {A}. You cannot afford another one."
      ]
    },
    bad: {
      good: [
        "{A}, the challenge was a bright spot, but that photo is not acceptable at this stage.",
        "You showed fight in the challenge, {A}, but the photo is a surrender.",
        "The challenge proved you’re still in this, {A}, but the photo is trying to send you home.",
        "We saw a glimmer of hope in the challenge, {A}, extinguished by this photo.",
        "You worked hard where others saw you, {A}, but you didn’t work hard where it counts most.",
        "Your challenge performance was your lifeline, {A}. Your photo tried to cut it.",
        "You were a team player in the challenge, {A}, but you were a solo act of disaster in the photo.",
        "The challenge was your redemption arc, {A}. The photo was the tragic ending.",
        "You understood the assignment in the challenge, {A}, and completely misunderstood it in the photoshoot.",
        "You showed personality and grit in the challenge, {A}, and left both in the makeup chair.",
        "You earned your keep in the challenge, {A}, and squandered it in front of the lens.",
        "The challenge was your argument to stay, {A}. The photo is the prosecution’s best evidence.",
        "You were memorable for the right reasons earlier, {A}, and unforgettable for the wrong reasons now.",
        "You built a little momentum, {A}, and then drove it straight off a cliff.",
        "You were coherent and focused in the challenge, {A}, and a scattered mess in the photo.",
        "The challenge showed you can listen, {A}. The photo shows you didn’t hear a thing.",
        "You were present and engaged, {A}, until the moment that defined your week.",
        "You gave us something to hold onto, {A}, and then you let it go.",
        "The challenge was your strength, {A}. The photoshoot was your catastrophic weakness.",
        "You proved you have the tools, {A}, and then refused to use the most important one.",
        "You were in the game during the challenge, {A}, and you forfeited during the photoshoot.",
        "You showed resilience in the face of one test, {A}, and collapsed in the face of another.",
        "You gave us a reason to believe in you, {A}, and then gave us every reason to doubt.",
        "The challenge was your apology, {A}. The photo was another mistake.",
        "You fought for your place, {A}, and then posed like you didn’t want it.",
        "You were a contender in the challenge, {A}, and an afterthought in the photo.",
        "You displayed a skill set, {A}, and then failed the core competency.",
        "You were part of the conversation, {A}, until this photo ended it.",
        "You had a path to safety, {A}, and you walked right off it.",
        "The challenge was your saving grace, {A}. This photo may have nullified it."
      ],
      mid: [
        "{A}, you’re fading. We still don’t know who you are as a model.",
        "You’re becoming a ghost in this competition, {A}. Your presence is barely felt.",
        "We’ve forgotten what you’re capable of, {A}, because you’ve stopped showing us.",
        "You’re a non-factor this week, {A}. That’s worse than being a bad one.",
        "You’re not making an impression, {A}, good or bad. You’re just… there.",
        "Your identity is blurry, {A}. We need a sharp, clear picture of who you are.",
        "You’re letting the weeks pass you by, {A}, instead of marking them as your own.",
        "You’re a question without an answer, {A}, and time is running out to provide one.",
        "You’re not evolving, {A}. You’re static, and static things get left behind.",
        "You’re a sketch when we need a finished painting, {A}.",
        "You’re background noise, {A}, in a room full of solos.",
        "You’re not claiming your space, {A}. You’re waiting for it to be given, and it won’t be.",
        "You’re a maybe in a world of definite yeses and definite nos, {A}.",
        "Your light is so dim, {A}, we’re squinting to see it.",
        "You’re not in the race, {A}; you’re just on the track.",
        "You’re a template of a model, {A}, not an original.",
        "You’re giving us nothing to hold onto, {A}. No point of view, no passion, no fire.",
        "You’re a placeholder in your own journey, {A}.",
        "You’re becoming forgettable, {A}, and that is the kiss of death here.",
        "You’re not bad, {A}, you’re blank. And blank is worse.",
        "You’re a whisper in a shouting match, {A}.",
        "You’re hiding in plain sight, {A}, and the hiding spot is about to be exposed.",
        "You’re not building a portfolio, {A}; you’re collecting snapshots.",
        "You’re a story we’ve lost the plot to, {A}.",
        "You’re not competing; you’re occupying a seat, {A}.",
        "You’re a reflection of everyone else’s light, {A}, with none of your own.",
        "You’re a 'could have been' in the making, {A}.",
        "You’re not leaving a mark, {A}. You’re just taking up space.",
        "You’re a mystery we’re losing interest in solving, {A}.",
        "You’re fading to gray, {A}, in a competition that demands color."
      ],
      bad: [
        "{A}, this week wasn’t it. The performance reads defeated.",
        "You’ve given up, {A}, and it’s written in every choice you made.",
        "This was a catastrophic week, {A}. There is no silver lining.",
        "You’re not even trying to hide the fact that you’ve checked out, {A}.",
        "The will to fight is gone, {A}, and without it, you have nothing.",
        "You’re going through the motions with zero heart, {A}. It’s painful to watch.",
        "You’re defeated, {A}, and you’ve defeated yourself.",
        "This is not the model who walked into this competition, {A}. What happened?",
        "You’re a shell, {A}, and the substance has completely evaporated.",
        "You’re not just having a bad week, {A}; you’re having a breakdown.",
        "The spark is not just dim, {A}; it’s out. We’re looking at ashes.",
        "You’re drowning, {A}, and you’re not even reaching for the surface.",
        "You’ve lost the plot, the passion, and the point, {A}.",
        "This is a surrender, {A}, and we don’t crown surrenders.",
        "You’re not modeling, {A}; you’re just existing in front of a camera.",
        "The desire is missing, {A}, and without it, the talent is irrelevant.",
        "You’re letting the dream slip through your fingers, {A}, without a fight.",
        "You’re a shadow of your former self, {A}, and the former self wasn’t here long enough.",
        "You’re not just at the bottom; you’ve dug yourself a hole, {A}.",
        "This is rock bottom, {A}. The only question is if you can push off.",
        "You’re not a contender this week, {A}. You’re a cautionary tale.",
        "You’ve disconnected, {A}, from the competition, from the camera, from us.",
        "You’re performing from a place of obligation, {A}, not aspiration.",
        "The light in your eyes has been replaced by resignation, {A}.",
        "You’re not just losing, {A}; you’ve accepted the loss.",
        "You’re a walking apology this week, {A}, with nothing to back it up.",
        "You’ve hit a wall and decided to lie down, {A}.",
        "This is not a stumble, {A}; it’s a collapse.",
        "You’re letting your own fears win, {A}, and they’re winning convincingly.",
        "The journey ends if you don’t change course, {A}. This week was the warning sign."
      ]
    }
};
