window.ANTM_FINAL_PANEL_SPEECHES = {
    good: [
      "{A}, you delivered when it mattered most. You have the look, the drive, and the discipline. This journey was defined by your relentless pursuit of excellence.",
      "From the first week, you set the pace. {A}, you never looked back, and tonight you've proven you were a frontrunner from the start. Your consistency was your superpower.",
      "{A}, you didn't just compete; you redefined the standard for everyone else. Your portfolio from this competition is a masterclass in modern modeling.",
      "You weren't just a model in this competition, {A}, you were a force of nature. Every challenge was met with focus, and every photoshoot was elevated by your presence.",
      "{A}, your name will be remembered from this season. You didn't just participate; you dominated, week after week.",
      "Every photo, every challenge, every step on the runway was a statement. {A}, you declared yourself a star, and we believed you from day one.",
      "{A}, you have the face, the poise, and the unshakable heart of a champion. Your journey has been one of undeniable growth and power.",
      "You navigated the pressure with grace and attacked every brief with intelligence. {A}, you made the difficult look effortless, and that is the mark of a true professional.",
      "{A}, you made the camera fall in love with you, and you made the judges believe in you. Your body of work here is extraordinary.",
      "This was a story of growth, power, and unwavering consistency. {A}, you wrote every chapter with intention and fire.",
      "You didn't just walk into this competition, {A}, you claimed it as your own. Your confidence was earned through flawless execution.",
      "{A}, your potential was clear from the start, but watching you realize it has been the privilege of this season.",
      "You were a photographer's dream, a client's wish list, and a judge's revelation. {A}, your versatility and precision set you apart.",
      "In a room full of talent, you didn't just stand out—you set the bar. Your journey has been a highlight reel, {A}.",
      "{A}, you combined raw talent with a relentless work ethic. You showed up, every single time, ready to deliver magic.",
      "You didn't just adapt to this competition, {A}; you mastered its every demand. Your performance was a blueprint for success.",
      "Your journey was a masterclass in resilience and artistry. {A}, you faced every obstacle and turned it into an opportunity.",
      "From potential to powerhouse. {A}, you transformed before our eyes into a model ready for the global stage.",
      "You never played it safe. You took risks, you showed vulnerability, and you shined brighter for it. {A}, your courage defined your journey.",
      "This isn't just about a single moment, {A}. It's about a stunning body of work, and yours was impeccable from start to finish.",
      "{A}, you have the 'it' factor that can't be taught, and you wielded it with intelligence and control throughout this competition.",
      "You led when others followed, you shined when others faded. {A}, your presence commanded attention every single week.",
      "You treated every week like it was the finale. {A}, that unwavering focus and fire are what made your journey so spectacular.",
      "Your name wasn't just called; it was earned, week after week, in stunning photographs and commanding performances.",
      "You didn't just want this, {A}; you worked for it, you fought for it, and you embodied what it means to be a top model.",
      "The world was watching a star in the making, and you delivered. {A}, your journey has been nothing short of brilliant.",
      "You balanced artistry with commercial appeal, edge with elegance. {A}, you proved you are the complete, modern package.",
      "You didn't just meet the brief; you became the brief. {A}, your creative vision elevated every single shoot you were in.",
      "This journey is a testament to your professionalism, your passion, and your raw talent. {A}, you have left an indelible mark.",
      "You started as a contender and finished as a definitive force. {A}, your path through this competition was paved with excellence."
    ],
    mid: [
      "{A}, you are talented and you fought hard — but your journey was marked by peaks and valleys that kept you from the very top.",
      "You showed us moments of brilliance, {A}, but consistency was the missing piece in your puzzle this season.",
      "{A}, you have a lot of heart and potential. This journey was about finding your footing, and you found it, just a little later than some.",
      "To come this far is an achievement, {A}. Your journey was one of resilience, of getting back up every time you stumbled.",
      "You stood in the ring with the best, {A}. Your journey wasn't a straight line to the top, but it was a fight every step of the way.",
      "The difference was often in the details, {A}. Your journey had its bright spots, but also its overlooked moments.",
      "You didn't have the smoothest ride, {A}, but you never gave up. Your journey is a testament to your determination.",
      "Your portfolio has its gems, {A}. This journey was about learning, sometimes the hard way, what it takes to shine.",
      "You made us believe in your potential, {A}. Your journey was a promise of what could be, with flashes of what is.",
      "This wasn't a story of dominance, {A}, but a story of grit. You hung in there, week after week, proving your durability.",
      "You walked a tougher path than most, {A}. Your journey was about overcoming your own doubts as much as the competition.",
      "{A}, your potential has always been your calling card. This journey was about beginning to unlock it, piece by piece.",
      "You were often in the mix, {A}. Your journey was one of being a solid, reliable presence, if not always a groundbreaking one.",
      "In a season of high drama, yours was a quieter journey, {A}. But quiet doesn't mean without merit or fight.",
      "{A}, you combined likeability with a strong work ethic. Your journey was about being a team player who could also stand alone.",
      "You adapted, sometimes slowly, but you always adapted. {A}, your journey was one of gradual, hard-won evolution.",
      "Your journey was a lesson in perseverance, {A}. You faced critiques head-on and worked to improve, week by week.",
      "From raw talent to a more polished performer, {A}. Your journey was a visible arc of growth, if not a meteoric rise.",
      "You played it safe at times, and it cost you. {A}, your journey is a reminder that in this game, safe is often a risk.",
      "This journey wasn't defined by a single iconic moment, {A}, but by a collection of steady, workmanlike efforts.",
      "{A}, you have the tools. Your journey here was about learning how to use them all effectively under pressure.",
      "You followed when you could have led, {A}. Your journey had moments of hesitation that held back your true spark.",
      "You treated some weeks like they were disposable, {A}, and that inconsistency defined the shape of your journey.",
      "Your name was called, but sometimes just barely. {A}, your journey was a narrow escape as often as it was a triumph.",
      "You wanted this, {A}, but the hunger wasn't always visible in your performance. Your journey had a flickering flame.",
      "The world saw a model with clear potential, {A}. Your journey was the first chapter, not the climax, of your story.",
      "You struggled to find the balance, {A}, sometimes leaning too commercial, sometimes too artistic. Your journey was about searching for that middle ground.",
      "You met the brief, but rarely exceeded it. {A}, your journey was competent, reliable, but often lacked the 'wow' factor.",
      "This journey is a solid foundation, {A}. It's not the glittering tower some built, but it's a base you can build upon.",
      "You started as a question mark and finished as a contender, {A}. Your journey was one of answering doubts, one week at a time."
    ]
};