window.ANTM_PHOTOSHOOT_COMMENTS = {
  positive: [
"{A} owns the frame with a presence that's both powerful and nuanced.",
"The camera loves {A}; every shot has a palpable, electric energy.",
"{A} sells the fantasy completely. This is next-level storytelling.",
"Flawless technique meets raw emotion. {A} is in a league of their own.",
"That's a money shot. {A} just delivered the cover.",
"The subtle tension in {A}'s posture is masterful. So much said without words.",
"{A} moves like liquid; every transition between poses is intentional and beautiful.",
"The eye contact is devastating. {A} connects directly with the viewer.",
"{A} makes the difficult look effortless. A true professional at work.",
"The light sculpts {A} perfectly. They understand how to work with it intuitively.",
"{A}'s face is a mood board in itself. Endless expression.",
"This isn't modeling; it's performance art. {A} is the concept.",
"The confidence is contagious. {A} elevates the entire team's work.",
"{A} finds the perfect balance between strength and vulnerability.",
"Dynamic, fresh, and modern. {A} is defining the look for this season.",
"Every detail, from fingertip to gaze, is meticulously crafted and alive.",
"{A} has the rare ability to look both timeless and utterly of-the-moment.",
"The chemistry with the environment is perfect. {A} belongs in this world.",
"A chameleon. {A} completely transforms to fit the narrative.",
"The shot is alive with movement, even in stillness. Incredible.",
"{A} doesn't just wear the clothes; they give them meaning and attitude.",
"Precision and instinct in perfect harmony. {A} is a natural.",
"The energy in the room shifted when {A} stepped in front of the lens.",
"{A} gives the photographer endless options—every frame is usable.",
"Sophisticated, editorial, and cool without trying. {A} has the 'it' factor.",
"The jawline, the neck, the shoulders—every angle is considered and striking.",
"{A} brings an intelligence to the pose that adds layers to the image.",
"Pure star power. {A} has the kind of presence you can't teach.",
"The commitment to the character is total. No hesitation, just belief.",
"{A} works the silhouette of the garment to its maximum potential.",
"A masterclass in subtlety. The quietest shot is often the strongest.",
"{A} and the camera are in a private conversation. We're just witnessing it.",
"The body language tells a complete story from head to toe.",
"{A} makes complex posing look like a natural state of being.",
"Editorial gold. {A} could make a grocery bag look high-fashion.",
"There's a thought behind the eyes. It's not a blank stare; it's a narrative.",
"{A} balances strength and grace in a way that is utterly compelling.",
"The shot feels discovered, not staged. {A} creates that authenticity.",
"A magnetic pull. Your eye goes directly to {A} and stays there.",
"{A} understands their best angles but isn't afraid to push beyond them.",
"The texture and mood {A} brings are exactly what the brief called for—and more.",
"Effortless cool. {A} looks like they just happened to be this perfect.",
"The pose has architecture and flow. It's dynamic sculpture.",
"{A} delivers a specific, requested emotion on cue, every time.",
"Collaborative and generative. {A} builds on direction and runs with it.",
"The profile shot is exquisite. {A} has a line that belongs in a sketchbook.",
"{A} commands attention without demanding it. A quiet power.",
"Versatility within a single shoot. {A} shows range without losing the thread.",
"The embodiment of the brand's ethos. {A} is the muse.",
"A definitive performance. This is what we came for."
  ],
  neutral: [
"{A} is reliable and consistent. We're getting the job done.",
"The shots are technically fine, but they're missing a point of view.",
"{A} hits the mark without surprising us. It's competent.",
"There's a good base here, but {A} needs to push the expression further.",
"The body is posed, but the eyes aren't fully engaged in the story.",
"{A} is giving us what we asked for, literally. Interpretation is minimal.",
"It's a pleasant shot. {A} looks good, but the image isn't arresting.",
"{A} relies on a few safe, go-to poses. We need to see more variety.",
"The potential is visible, but {A} seems hesitant to fully commit.",
"A solid catalog performance. It will sell the product clearly.",
"{A} is working hard, and it shows. We need to find more ease.",
"The face is strong when still, but loses energy during movement.",
"{A} is responsive to direction but doesn't yet add their own spin.",
"We're getting one note consistently. Let's explore a different octave.",
"The shot is usable, but it sits in the middle of the pack.",
"{A} understands the 'how' of posing but not yet the 'why' for this concept.",
"The technicals are correct: posture, angles. The soul is quieter.",
"{A} looks like a model in clothes, not a person inhabiting the clothes.",
"It's close. The elements are there, but they haven't clicked into place yet.",
"{A} is thinking too much. We can see the calculation in the eyes.",
"The energy is polite when it needs to be powerful.",
"Good bones. With stronger direction, this could become great.",
"{A} delivers a standard 'fashion face.' We need something more specific.",
"The connection with the prop/environment feels transactional, not natural.",
"A workmanlike effort. It fulfills the brief's basic requirements.",
"{A} has moments of brilliance, but they're not sustained.",
"The pose is interesting, but the expression doesn't match its intensity.",
"We're seeing the pose, not the person. There's a wall up.",
"{A} is fighting their natural body line a bit. It creates stiffness.",
"The shot is fine for a secondary image or an online gallery.",
"{A} needs to find the motivation behind the move, not just the shape.",
"It's generic. {A} could be selling any product in any campaign.",
"The light is doing most of the work. {A} needs to meet it halfway.",
"A decent blank canvas. It requires more post-production storytelling.",
"{A} is imitating a reference instead of creating something new.",
"The hands/foot placement is a bit awkward, breaking the line.",
"There's a disconnect between the fierceness of the body and softness of the face.",
"{A} is playing it safe to avoid making a mistake. We need a risk.",
"The shot is forgettable five minutes after we take it.",
"{A} is capable, but the spark of instinct isn't firing consistently.",
"We're getting 'day one' energy, not 'day of the shoot' energy.",
"The composition is right, but the emotional weight is missing.",
"{A} looks like they're waiting for approval after each shot.",
"It's a template performance. Effective, but not distinctive.",
"The garment is the focus, not {A}. That can be good or bad depending on the goal.",
"{A} needs to ground themselves more; the energy feels floaty and unfocused.",
"A serviceable performance. It won't be the hero shot, but it'll be in the layout.",
"{A} is over-pronouncing the pose, making it feel theatrical instead of authentic.",
"We've seen this pose from {A} before. Time to dig deeper into the repertoire."
  ],
  negative: [
"{A} disappears into the background. The set is wearing them.",
"{A} has one 'look' and it's wrong for every single setup we try.",
"{A} is arguing with the creative director about the vision. Unprofessional.",
"{A} is blinking or making a strange face at the exact wrong moment. Consistently.",
"{A} is completely upstaged by a less experienced model on set.",
"{A} is constantly checking their own reflection, breaking the flow.",
"{A} is copying a pose from memory without understanding its geometry.",
"{A} is fighting against the photographer's every direction.",
"{A} is making the clothes look awkward and ill-fitting through bad posing.",
"{A} is making the same mistake repeatedly, despite clear correction.",
"{A} is over-complicating simple direction, resulting in a mess.",
"{A} is overposing to the point of caricature. It's all affectation.",
"{A} is phoning it in. Zero effort, zero passion, zero result.",
"{A} is physically present but mentally absent. The eyes are empty.",
"{A} is relying on old tricks that are dated and no longer effective.",
"{A} is so focused on a 'perfect' angle they've become a statue.",
"{A} is staring directly into the lens with zero intention. It's confrontational in the wrong way.",
"{A} is sweating the small details and losing the entire mood of the shoot.",
"{A} is trying to be someone else entirely, and it's a poor imitation.",
"{A} is trying to force a connection that isn't there. It reads as insincere.",
"{A} looks deeply uncomfortable in their own skin. It's painful to watch.",
"{A} looks like they'd rather be anywhere else. It saps the team's morale.",
"Every shot has the same dead-eyed, generic smile. No range, no soul.",
"It's giving 'amateur hour.' The gap between intent and execution is vast.",
"It's like {A} has never seen a camera before. Deer-in-headlights energy.",
"The 'modeling' is all in the face; the body is just a static stand.",
"The body language is closed off and defensive. It repels the lens.",
"The concept is completely lost. {A} is just standing there in a costume.",
"The connection with other models in the shot is forced and awkward.",
"The energy is completely flatlined. No dynamism, no life.",
"The energy is petulant and uncooperative. It's draining the clock.",
"The expression is a blank mask. No thought, no emotion, no story.",
"The expression is stuck in a weird pout/grimace that reads as pained.",
"The face and body are telling two completely unrelated stories.",
"The hands are a disaster—claw-like, stiff, or completely forgotten.",
"The movement between poses is awkward and jarring, not fluid.",
"The overall impression is cheap. It undermines the production value.",
"The performance is so internal it doesn't translate to the lens. It's private.",
"The posing is stiff and unnatural, like a mannequin being moved.",
"The posture is sloppy—rounded shoulders, hunched neck. No line.",
"The shot is unusable due to {A}'s lack of physical control in the pose.",
"The shots look like bad test polaroids, not final campaign imagery.",
"There's a lack of basic physical awareness—where limbs are in space.",
"There's a visible desperation to 'get it right' that ruins any sense of ease.",
"There's zero collaboration. It feels like pulling teeth to get a usable shot.",
"They look like a civilian who won a contest to be in a photoshoot.",
"They're literally trembling with nerves. It's affecting the clothing drape.",
"They're treating the high-fashion concept like a casual snapshot.",
"This is a waste of the team's talent and the client's budget. A total misfire.",
"This is giving 'first-day-of-modeling-school' nerves. No command."
  ]
};
