window.ANTM_EVENTS = {
  // ------------------------------------------------------
  // SOLO EVENTS
  // ------------------------------------------------------
  solo_neutral: [
    "{A} stands before a mirror, cycling through a series of smizes and pouts, scrutinizing each one.",
    "{A} rehearses a silent, imaginary runway walk across the living room, mouthing 'photo shoot' at the end.",
    "{A} tries to mentally tally how many confessionals they've done this week, wondering if it's enough.",
    "{A} studies a supermodel's walk on their phone, their feet making tiny, repetitive motions on the floor.",
    "{A} invents a bizarre new stretching routine, hoping the cameras will notice and make it their 'thing'.",
    "{A} lays out their portfolio photos, rearranging them for maximum impact and reliving each moment.",
    "{A} practices deflecting personal questions in the mirror, perfecting a polished, non-answer smile.",
    "{A} secretly writes a ranked list of the other models in their journal, based on 'threat level'.",
    "{A} experiments with an extreme, artistic makeup look in their room, just to see if they can.",
    "{A} stares at their own reflection in a dark window for a long time, lost in thought.",
    "{A} fills several pages of a journal, writing intently for over an hour.",
    "{A} performs an elaborate, ten-step skincare ritual in the bathroom with intense focus.",
    "{A} spends their downtime sketching fashion designs in a notebook, lost in a creative world.",
    "{A} meticulously reorganizes the entire shared wardrobe, color-coding and folding everything.",
    "{A} practices a series of signature poses in a quiet corner, holding each for a full minute.",
    "{A} flows through a long, quiet yoga session in the living room, focusing on their breath.",
    "{A} has a hushed, lengthy conversation on the house phone, their expression unreadable.",
    "{A} meticulously polishes a single pair of shoes for twenty minutes, focusing on nothing else.",
    "{A} tries to identify their own 'brand' by writing down adjectives on a notepad, then crossing most out.",
    "{A} quietly practices their signature on scraps of paper, imagining autographing photos.",
    "{A} counts the number of times they've been in the top group versus the bottom, calculating odds.",
    "{A} stares at a blank wall, mentally rehearsing their 'what this opportunity means to me' speech.",
    "{A} reorganizes their toiletries by color and size, creating a perfectly aesthetic shelf.",
    "{A} attempts to meditate but ends up mentally critiquing their own breathing technique.",
    "{A} flips through a fashion magazine, not reading it, but studying the models' jawlines and hand placement.",
    "{A} writes a letter home they'll never send, filled with exaggerated confidence.",
    "{A} practices walking with a book balanced on their head while making intense eye contact with their reflection.",
    "{A} tries to remember every single piece of criticism they've received, writing them down as 'areas for growth'.",
    "{A} spends an hour trying to perfect a single, elusive facial expression—somewhere between mystery and approachability.",
    "{A} creates a tiny, private photo album on their phone of just their best shots from the competition so far.",
    "{A} hums the theme music from past seasons' final runway shows while pacing.",
    "{A} carefully folds every item of clothing they own, treating it like a sacred ritual.",
    "{A} tries to learn how to tie a scarf in seven different 'model-off-duty' ways from a YouTube tutorial.",
    "{A} stands in different patches of light in the house, testing which angles make their skin look best.",
    "{A} whispers potential answers to imagined interview questions under their breath while making coffee.",
    "{A} spends a long time looking at their hands, flexing and posing them from every angle.",
    "{A} creates a detailed, completely unrealistic schedule for their hypothetical 'first year as a top model'.",
    "{A} practices entering and exiting a room, trying to nail the exact energy of 'arriving'.",
    "{A} tries to press a wrinkle out of a garment with their hands, over and over, with intense concentration.",
    "{A} listens to the same song on repeat, visualizing a music video they would star in.",
    "{A} attempts to sketch a portrait of themselves from memory, but gives up halfway through.",
    "{A} cleans a spot on the mirror with their sleeve, then stares at their own cleared reflection.",
    "{A} tries to calculate the exact caloric intake of their meals for the day, then abandons the math.",
    "{A} practices the art of the 'candid laugh' for photos, forcing chuckles in the silent room.",
    "{A} holds different facial expressions for a full minute each, trying to build 'face muscle memory'.",
    "{A} writes down the names of all the judges, then tries to assign each one an animal they remind them of.",
    "{A} tries to sleep, but can be seen tracing imaginary runway patterns on the ceiling with their finger."
  ],

  // ------------------------------------------------------
  // TWO-PERSON EVENTS
  // ------------------------------------------------------
  two_neutral: [
    "{A} asks {B} for their brutally honest opinion on their best and worst photo from the last shoot.",
    "{B} casually asks {A} which judge's critique stung the most this week.",
    "{A} and {B} trade tips on how to walk in impossible heels without breaking an ankle.",
    "{A} tries to teach {B} their method for summoning real tears during emotional shoots.",
    "{B} and {A} have a low-voiced discussion about the unspoken hierarchy forming in the house.",
    "{A} points out a small camera blind spot to {B}, sharing a moment of conspiratorial awareness.",
    "{B} asks {A} if they think the producers are editing them to be the 'villain' of the season.",
    "{A} and {B} whisper about which past winner's career path they'd most like to follow.",
    "{B} helps {A} rehearse answers to a judge's question that tripped them up last panel.",
    "{B} asks {A} for their take on whether a certain outfit is 'too commercial' or 'just right.'",
    "{B} confesses to {A}, laughing, that they completely blanked on a judge's name earlier.",
    "{B} quietly asks {A} if they think the judges have a clear favorite yet.",
    "{A} compliments {B}'s choice of pajamas, calling them surprisingly chic.",
    "{B} tells {A} a corny, unfunny joke from their childhood, and they both smirk.",
    "{A} and {B} debate whether it's better to be memorable for one great shot or consistently good in every shot.",
    "{B} asks {A} if they think the stylists have a favorite model they always give the best clothes to.",
    "{A} and {B} try to guess what the theme of next week's photoshoot might be, based on cryptic crew comments.",
    "{B} shows {A} a strange rash and asks, in all seriousness, if they think it's 'photoshoot-worthy' or should be hidden.",
    "{A} and {B} have a hushed conversation about which model's 'backstory' they find the most strategically useful.",
    "{B} asks {A} for a second opinion on two nearly identical lipstick shades for their confessional look.",
    "{A} and {B} compare notes on how much sleep they're actually getting, both complaining but in a competitive way.",
    "{B} points out a specific camera to {A} and theorizes whether it's always on or just for wide shots.",
    "{A} and {B} discuss the ethics of 'borrowing' another model's accessories without asking first.",
    "{B} asks {A} if they think crying in panel is a sign of weakness or a strategic play for sympathy.",
    "{A} and {B} try to remember the name of the sound guy, realizing they only know the judges' and photographer's names.",
    "{B} confesses to {A} that they've started dreaming in runway walks and photoshoot concepts.",
    "{A} and {B} have a tactical discussion about the best spot to stand in group shots to get noticed.",
    "{B} asks {A} what their plan is for the inevitable 'dreaded makeover' episode.",
    "{A} and {B} share a silent, knowing look when another model starts practicing their 'humble' confessional speech nearby.",
    "{B} shows {A} a text from home and asks if the tone sounds 'supportive enough' or vaguely disappointed.",
    "{A} and {B} try to determine if the lighting in the kitchen is more flattering in the morning or at night.",
    "{B} asks {A} if they think the prize package is actually worth all the stress, or just the title.",
    "{A} and {B} discuss the merits of various model 'personas'—the diva, the girl-next-door, the quirky artist.",
    "{B} points out to {A} which plants in the house are real and which are fake, as if this is vital intelligence.",
    "{A} and {B} have a brief, awkward conversation about what they'll do if they're eliminated first.",
    "{B} asks {A} if they've noticed a specific producer favoring or ignoring any particular model.",
    "{A} and {B} try to recall the first thing they said in their very first confessional, both drawing a blank.",
    "{B} wonders aloud to {A} if the food they're served is specifically designed to keep them 'camera-ready'.",
    "{A} and {B} debate which is harder: a surprise runway or a surprise acting challenge.",
    "{B} asks {A} if they think their own voice sounds different on the recorded confessionals.",
    "{A} and {B} share a moment of mutual confusion over a vague piece of direction a judge gave that week.",
    "{B} tries to get {A}'s opinion on whether a certain facial feature of theirs is a 'signature' or a 'flaw'.",
    "{A} and {B} discuss the surreal experience of seeing their own face on the monitors during playback.",
    "{B} asks {A}, entirely seriously, if they think it's possible to practice having a better personality."
  ],

  two_positive: [
    "{A} gives {B} a genuine, heartfelt pep talk when they find them looking defeated.",
    "{B} spends an hour helping {A} refine their runway walk, offering supportive, specific tips.",
    "{A} surprises {B} by making their favorite snack and leaving it with a note.",
    "{A} and {B} stay up late sharing stories from home, laughing until their sides hurt.",
    "{A} does {B}'s makeup just for fun, and {B} is thrilled with the glamorous result.",
    "{A} and {B} start a spontaneous, silly dance party in the middle of the living room.",
    "{A} teaches {B} a unique posing trick they developed, sharing it freely.",
    "{B} listens quietly and supportively as {A} vents about a personal worry unrelated to the show.",
    "{A} gives {B} a sincere, unsolicited compliment on their kindness or strength of character.",
    "{A} and {B} invent an elaborate, ridiculous secret handshake.",
    "{A} stays up past midnight helping {B} master a painful, contorted pose from a shoot.",
    "{B} loudly defends {A}'s talent during a house debate, shutting down criticism from others.",
    "{A} and {B} create a subtle, secret signal to warn each other of nearby gossip.",
    "{B} uses their confessional time to praise {A}'s work ethic and growth, not their own.",
    "{A} and {B} have a raw, tearful conversation about their fears and dreams, caught on camera.",
    "{B} teaches {A} their signature, show-stopping runway spin, a move they usually keep secret.",
    "{B} tells {A}, 'You're the only real competition I see here,' with total respect.",
    "{B} brings {A} a cup of tea exactly how they like it, remembering the details from an offhand comment weeks ago.",
    "{A} and {B} spend an afternoon creating ridiculous, over-the-top 'model poses' for each other, collapsing into laughter.",
    "{B} lends {A} their lucky pair of earrings before a big photoshoot, insisting it's for 'good energy.'",
    "{A} helps {B} memorize a long script for a commercial challenge, performing all the other roles with exaggerated drama.",
    "{B} defends {A}'s creative choice during a group challenge when others doubt it, standing firm with them.",
    "{A} secretly arranges for {B}'s favorite snack to be in the pantry after they mentioned missing it days ago.",
    "{B} stays up with {A} to help them steam an entire rack of wrinkled clothing before an early call time.",
    "{A} and {B} create a silly, secret nickname for the most intimidating judge, diffusing the tension around them.",
    "{B} gives {A} a genuine, specific compliment about their kindness, not their modeling, when they need it most.",
    "{A} teaches {B} how to say 'I am a fierce model' in their native language for confidence before panel.",
    "{B} draws a funny caricature of {A} during a boring downtime, capturing their best feature perfectly, and gifts it to them.",
    "{A} and {B} promise to be each other's 'hype person' for the next runway, giving loud, obnoxious encouragement from the sidelines.",
    "{B} notices {A} is getting a blister from new shoes and, without a word, finds blister pads and leaves them on their bed.",
    "{A} shares a personal, non-competition-related fear with {B}, who listens without judgment or advice, just support.",
    "{B} uses their one phone call home to let {A} talk to their family for a few minutes when they're feeling particularly homesick.",
    "{A} and {B} start a tradition of sharing one good thing that happened each day, no matter how small.",
    "{B} helps {A} re-do their entire makeup after a meltdown, patiently and without making a fuss.",
    "{A} nominates {B} for a small, positive 'house award' they made up, presenting it with dramatic flair.",
    "{B} remembers the anniversary of {A}'s first-ever photoshoot and celebrates it with them quietly.",
    "{A} and {B} work out a silent communication system during challenges to help each other without breaking rules.",
    "{B} writes a list of {A}'s top five strengths as a model and slips it under their door after a tough critique.",
    "{A} volunteers to take the worse bed/bunk/room situation so {B} can have the more comfortable one.",
    "{B} teaches {A} a childhood game from their hometown, spending an hour playing it together to decompress.",
    "{A} and {B} make a pact to give one another completely honest, constructive feedback after every shoot from now on.",
    "{B} surprises {A} by styling a complete 'day off' look for them using only house clothes, making them feel seen.",
    "{A} stands up for {B} when another model tries to take credit for their idea in a team challenge.",
    "{B} secretly records a video on {A}'s phone of them nailing a difficult pose, so they can see their own success.",
    "{A} and {B} share headphones and listen to the same calming playlist while waiting for judging results.",
    "{B} tells {A}, 'Whatever happens, I'm glad I got to compete alongside you.'"
  ],

  two_negative: [
    "{A} and {B} get into a heated argument over who used the last of the expensive conditioner.",
    "{A} and {B} have a tense, silent standoff over who gets to use the house phone first.",
    "{A} makes a catty, under-the-breath remark about {B}'s performance in the last challenge.",
    "{A} and {B} trade thinly-veiled insults over breakfast, poisoning the morning mood.",
    "{A} loudly critiques {B}'s posture while they practice, calling it 'amateur.'",
    "{B} rolls their eyes so dramatically at something {A} says that the entire room notices.",
    "{B} implies, just loudly enough, that {A} is only here for their look, not any real skill.",
    "{B} 'jokes' to others that {A} must have flirted with the photographer to get a good shot.",
    "{A} and {B} engage in a war of passive-aggressive, backhanded compliments in every interaction.",
    "{B} tells a visibly upset {A} that their crying face 'isn't photogenic and looks desperate.'",
    "{A} 'accidentally' spills water on {B}'s outfit right before a challenge, claiming it was a clumsy mistake.",
    "{B} loudly mimics {A}'s signature walk in front of others, exaggerating their flaws to cruel laughter.",
    "{A} starts a rumor that {B} is only succeeding because they're having a secret affair with a producer.",
    "{B} sabotages {A}'s practice by giving them intentionally bad advice on a pose, leading to a terrible polaroid.",
    "{A} goes through {B}'s personal belongings when they're not there, looking for 'ammunition' to use against them.",
    "{B} tells the judges, during a one-on-one chat, that {A} has been bad-mouthing their creative direction behind their back.",
    "{A} steals a piece of jewelry or accessory that {B} was planning to wear for a shoot, then pretends to have 'found' it later.",
    "{B} records {A} venting in a private moment and plays a clipped, damning snippet for other models.",
    "{A} tells {B} that their family back home is 'embarrassed' by their performance on the show.",
    "{B} ruins {A}'s concentration before a runway by whispering last-minute, false critiques about their walk.",
    "{A} creates a fake social media profile pretending to be a fan who only posts vicious critiques of {B}'s photos.",
    "{B} 'forgets' to pass along a vital message from production to {A}, causing them to miss an important call time.",
    "{A} and {B} get into a physical altercation during a challenge, needing to be pulled apart by crew.",
    "{B} tells a crying {A} that their emotions are 'manipulative' and that everyone sees through them.",
    "{A} systematically turns the entire house against {B} by sharing selectively edited truths about their conversations.",
    "{B} throws away {A}'s lucky charm or personal memento, claiming they thought it was trash.",
    "{A} loudly questions, during a group meal, whether {B} has an eating disorder, creating an unbearably awkward silence.",
    "{B} purposefully mispronounces {A}'s name repeatedly after being corrected, as a power move.",
    "{A} accuses {B} of racism or prejudice during an argument, using it as a tactical weapon rather than a genuine grievance.",
    "{B} tells {A} that their best friend in the house is only using them for an alliance and talks trash about them constantly.",
    "{A} deliberately ruins a piece of {B}'s artwork or craft from a creative challenge, calling it 'an improvement.'",
    "{B} gaslights {A}, insisting they never said something they definitely said, making {A} question their own sanity.",
    "{A} uses {B}'s deepest insecurity, confessed in confidence, as a punchline during a group confessional.",
    "{B} falsely tells production that {A} has been violating a major rule, hoping to get them disqualified.",
    "{A} and {B} engage in a screaming match so intense that a cameraman has to step in to de-escalate.",
    "{B} gives {A} a fake, backhanded compliment in front of a judge, designed to subtly undermine their work.",
    "{A} starts a chant against {B} during a runway rehearsal, getting other models to join in the mockery.",
    "{B} cuts a small, barely noticeable hole in {B}'s favorite garment right before a crucial photoshoot.",
    "{A} tells {B} they don't deserve their spot in the competition and should just quit to save everyone the time.",
    "{B} looks {A} dead in the eye and says, 'You will never be a real model.'"
  ],

  // ------------------------------------------------------
  // THREE-PERSON EVENTS
  // ------------------------------------------------------
  three_neutral: [
    "{A}, {B}, and {C} have a strategic huddle, discussing which elimination would best help their own games.",
    "{C} tries to mediate a tense debate between {A} and {B} over who deserves the first confessional slot.",
    "{A}, {B}, and {C} analyze the house's social dynamics like chess pieces, predicting the next target.",
    "{C} leads {A} and {B} in practicing their 'shocked and supportive' reaction faces for eliminations.",
    "{A}, {B}, and {C} pool their intel, sharing each judge's subtle pet peeves they've observed.",
    "{C} walks in on {A} and {B} in a private chat, causing an awkward pause filled with forced small talk.",
    "{A}, {B}, and {C} engage in a tense but civil negotiation over the one rack of designer clothes.",
    "{B} tries to get {A} and {C} to settle a passionate, pointless debate about the best pizza topping.",
    "{B} tells {A} and {C} a long, detailed story about their quirky hometown.",
    "{A}, {B}, and {C} discuss their all-time favorite fashion photographers and iconic shoots.",
    "{B} teaches {A} and {C} a simple breathing exercise to manage pre-panel nerves.",
    "{B} shares a meme they remembered with {A} and {C}, sparking a fit of shared, silly laughter.",
    "{A}, {B}, and {C} talk about what they miss most from home—family, pets, or favorite foods."
  ]
};