window.WOTW_EVENTS = {
  solo_neutral: [
    "{A} sips coffee alone on the patio, watching the sun come up.",
    "{A} hums to themselves while folding laundry in silence.",
    "{A} stares at the memory wall, lost in thought.",
    "{A} reorganizes the fridge just to keep busy.",
    "{A} flips through a magazine someone left behind.",
    "{A} waters the plants and whispers, 'you’re doing better than some people here.'",
    "{A} takes a nap in the lounge, half-listening to distant laughter.",
    "{A} writes imaginary headlines about house drama in their head.",
    "{A} lingers near the pool, overhearing a conversation not meant for them.",
    "{A} paces the hallway, debating whether to clear the air with someone.",
    "{A} cheers themself up by dancing in the mirror.",
    "{A} storms out of the kitchen muttering that everyone’s fake.",
    "{A} admits privately that they’re proud of how far they’ve come.",
    "{A} watches the group talk and smiles, quietly rooting for everyone.",
    "{A} calls themself 'the only real one left' under their breath.",
    "{A} rewrites a mental list of who’s 'dead to them' before dinner.",
    "{A} paces the hall rehearsing the perfect one-liner for their next blow-up.",
    "{A} mutters that people confuse kindness for weakness.",
    "{A} isolates themselves from everyone, hoodie up and headphones on.",
    "{A} tidies their corner of the bedroom without saying a word.",
    "{A} watches the living room chaos from the stairs, expression unreadable.",
    "{A} cooks a late-night snack while half the house naps.",
  ],
  two_neutral: [
    "{A} and {B} chat casually about their hometowns.",
    "{A} and {B} sit by the pool comparing favorite snacks.",
    "{A} and {B} swap stories about awkward past relationships.",
    "{A} and {B} wash dishes together while humming an old song.",
    "{A} and {B} share a blanket on the couch while talking about family.",
    "{A} and {B} laugh about how messy the house has gotten.",
    "{A} and {B} talk about what life will feel like after the show.",
    "{A} and {B} joke that they’ve both become neat freaks in here.",
    "{A} and {B} play a quick game of cards to pass time.",
    "{A} and {B} trade stories about their worst roommates ever.",
    "{A} and {B} compare who snores louder at night.",
    "{A} and {B} spend the afternoon doing absolutely nothing productive.",
    "{A} and {B} chat about food cravings they’ll indulge after filming.",
    "{A} and {B} laugh about inside jokes no one else understands.",
    "{A} and {B} talk through small misunderstandings and move on easily.",
    "{A} and {B} walk slow laps discussing how to avoid injury.",
    "{A} and {B} stretch back-to-back and nod in sync.",
    "{A} and {B} quietly observe who trains with who from the stairs.",
    "{A} and {B} split a protein snack and keep it moving.",
    "{A} and {B} do a light run through the courtyard.",
    "{A} and {B} spend the afternoon chatting in the lounge.",
    "{A} and {B} prepare a meal together in the kitchen.",
    "{A} and {B} accidentally wear matching outfits.",
    "{A} and {B} take turns using the bathroom mirror while getting ready.",
    "{A} and {B} discover they both like the same snack.",
    "{A} and {B} briefly discuss the day’s weather.",
  ],

  two_positive: [
    "{A} comforts {B} after a stressful day in the house.",
    "{A} compliments {B}’s outfit and they both laugh about fashion disasters.",
    "{A} shares a snack with {B} without being asked.",
    "{A} helps {B} calm down after an awkward group moment.",
    "{A} tells {B} that they’ve genuinely started to like them as a person.",
    "{A} and {B} stay up late talking about everything and nothing.",
    "{A} and {B} have a deep conversation about trust.",
    "{A} surprises {B} with coffee just the way they like it.",
    "{A} helps {B} fix a ripped shirt and jokes about being their stylist.",
    "{A} tells {B} they’ve got their back no matter what.",
    "{A} reassures {B} that the tension in the house isn’t all about them.",
    "{A} and {B} laugh until they cry over a silly misunderstanding.",
    "{A} checks in on {B} and says, 'you don’t have to fake it here.'",
    "{A} gives {B} the last clean towel because 'karma points matter.'",
    "{A} says they’d actually hang out with {B} in real life.",
    "{A} sticks up for {B} when others criticize them.",
    "{A} cheers {B} up with a funny impression.",
    "{A} supports {B} during a tense group meeting.",
    "{A} and {B} plan to look out for each other.",
    "{A} and {B} stay up late talking about their dreams.",
    "{A} reassures {B} they can trust them.",
    "{A} and {B} share a secret about someone else in the house.",
    "{A} tells {B} they’re one of the most genuine people here.",
  ],

  two_negative: [
    "{A} accuses {B} of talking behind their back.",
    "{A} says {B} has no backbone and just follows the crowd.",
    "{A} calls {B} a 'walking press release' for whoever’s winning.",
    "{A} tells everyone {B} has been scheming since day one.",
    "{A} and {B} get into a shouting match about loyalty.",
    "{A} mocks {B}’s ‘nice-guy routine’ in front of half the house.",
    "{A} rolls their eyes every time {B} speaks until {B} finally snaps.",
    "{A} says {B} tries too hard to act calm when they’re clearly scared.",
    "{A} claims {B} leaked private conversations for clout.",
    "{A} tells {B} they’ll 'crumble under pressure anyway.'",
    "{A} says {B} doesn’t deserve to be here and refuses to explain why.",
    "{A} calls {B} the 'house mascot' in a tone that’s not friendly.",
    "{A} and {B} nearly come to blows before others intervene.",
    "{A} shouts that {B} only forms alliances out of fear.",
    "{A} loudly declares that {B}’s apology 'doesn’t come with receipts.'",
    "{A} starts a sarcastic slow clap when {B} walks in the room.",
    "{A} says {B} is a chameleon and it’s time people noticed.",
    "{A} calls {B} ‘a walking PR move’ and walks out mid-conversation.",
    "{A} tells the entire house that {B} flips sides whenever convenient.",
    "{A} drunkenly announces that {B} ‘couldn’t win an argument, let alone a final.’",
    "{A} gets tipsy and points at {B} across the room: ‘Say it with your chest, not your whisper.’",
    "{A} tells the entire house that {B} rehearses confessional lines in the mirror.",
    "{A} and {B} argue about who left the kitchen messy.",
    "{A} accuses {B} of spreading rumors.",
    "{A} ignores {B} during a group conversation.",
    "{A} takes {B}'s food from the fridge without asking.",
    "{A} and {B} argue over who should get the better bed.",
    "{A} interrupts {B} constantly during a discussion.",
    "{A} laughs at {B}'s mistake.",
    "{A} rolls their eyes at something {B} says.",
    "{A} tells others that {B} can’t be trusted.",
    "{A} refuses to help {B} clean up a shared mess.",
    "{A} criticizes {B}'s cooking.",
    "{A} accuses {B} of being lazy.",
    "{A} and {B} get into a heated argument over chores.",
    "{A} calls out {B} for being fake.",
    "{A} says {B} is only here for attention.",
    "{A} gets annoyed at {B}'s constant talking.",
    "{A} gossips about {B} to someone else.",
    "{A} and {B} argue over who’s more popular in the house.",
    "{A} moves {B}'s belongings without permission.",
  ],
  three_neutral: [
    "{A}, {B}, and {C} cook dinner together while teasing each other.",
    "{A}, {B}, and {C} sit in the lounge telling embarrassing stories.",
    "{A}, {B}, and {C} debate who snores the loudest.",
    "{A}, {B}, and {C} laugh at {C}’s failed attempt to fix the coffee maker.",
    "{A}, {B}, and {C} chat about how weird it feels being on camera all the time.",
    "{A}, {B}, and {C} invent a fake talk show just to fill the silence.",
    "{A}, {B}, and {C} gossip lightly about who might be getting too confident.",
    "{A}, {B}, and {C} play a truth-or-dare game that spirals into laughter.",
    "{A}, {B}, and {C} talk about how much they miss real privacy.",
    "{A}, {B}, and {C} accidentally start a karaoke night with no music.",
    "{A}, {B}, and {C} discuss how unpredictable everyone’s moods have become.",
    "{A}, {B}, and {C} joke about who would survive best in the real world together.",
    "{A}, {B}, and {C} sit under blankets talking about nothing deep at all.",
    "{A}, {B}, and {C} speculate which pair secretly flirts when no one’s looking.",
    "{A}, {B}, and {C} laugh about how over-dramatic people get when bored.",
  ],
};

// Convert WOTW_EVENTS into a structure the simulator expects.
// The simulator uses events1 for solo neutral events, events2 for pair events (positive/neutral/negative), and events3 for trio events.
// We map the existing categories accordingly.  If a category is missing, default to an empty array.
window.WOTW_EVENTS_DATA = {
  events1: (window.WOTW_EVENTS && window.WOTW_EVENTS.solo_neutral) || [],
  events2: {
    positive: (window.WOTW_EVENTS && window.WOTW_EVENTS.two_positive) || [],
    neutral:  (window.WOTW_EVENTS && window.WOTW_EVENTS.two_neutral)  || [],
    negative: (window.WOTW_EVENTS && window.WOTW_EVENTS.two_negative) || []
  },
  events3: {
    // There are no explicitly positive trio events defined in WOTW_EVENTS.  Only neutral.
    positive: [],
    neutral:  (window.WOTW_EVENTS && window.WOTW_EVENTS.three_neutral) || []
  }
};
