/* bgasb_events_data.js
   BGASB House Events comment pools.

   Placeholders:
   - {A} = one person (events1)
   - {A}, {B} = two people (events2)
   - {A}, {B}, {C} = three people (events3)
*/

window.BGASB_EVENTS_DATA = {
  // -----------------------------------
  // EVENTS 1: Neutral-only (1 person)
  // -----------------------------------
  events1: [
    "{A} wakes up feeling themselves and starts the day confident.",
    "{A} does a full glam beat like it’s a confessional challenge.",
    "{A} paces the hallway, replaying last night’s drama in their head.",
    "{A} makes breakfast and pretends the house tension isn’t there.",
    "{A} claims a spot by the mirror and dares anyone to say something.",
    "{A} spends the morning doing stretches and quietly training.",
    "{A} takes over the music and turns the living room into a mini club.",
    "{A} sits outside alone, sipping a drink and plotting their next move.",
    "{A} cleans up the kitchen like nothing happened last night.",
    "{A} watches everyone’s interactions like it’s a chessboard.",
    "{A} practices their speech for nominations in the bathroom mirror.",
    "{A} replays the last challenge and mutters about what went wrong.",
    "{A} hides their snacks so nobody “accidentally” takes them.",
    "{A} walks around with sunglasses on indoors, unbothered on purpose.",
    "{A} talks to production in the corner and comes back smirking.",
    "{A} double-checks the fridge like someone’s been stealing.",
    "{A} takes a long shower and lets the hot water reset their mood.",
    "{A} claims a couch spot and refuses to move for anyone.",
    "{A} does laundry and throws shade without saying a word.",
    "{A} stays glued to their phone, scrolling like the drama isn’t real.",
    "{A} keeps their circle tight and doesn’t linger in group conversations.",
    "{A} practices endurance by doing stairs up and down the hallway.",
    "{A} pulls out a notebook and starts “counting votes” in silence.",
    "{A} quietly reorganizes the bedroom like it’s their territory.",
    "{A} cooks something loud and dramatic just to get attention.",
    "{A} spends the day laughing too hard at everything, and it feels calculated.",
    "{A} puts on heels for no reason and struts through the house.",
    "{A} avoids the main room completely and stays in their suite.",
    "{A} sits at the kitchen table like a boss waiting for reports.",
    "{A} whispers to themselves, rehearsing reads for later.",
    "{A} watches the security cameras feed like it’s movie night.",
    "{A} plays bartender and makes drinks with a suspiciously heavy pour.",
    "{A} tries to mediate the vibe, but stays careful not to pick sides.",
    "{A} puts on a face mask and listens through the door to gossip.",
    "{A} spends the afternoon doing hair and acting like the queen of the house.",
    "{A} walks the backyard, counting steps and staying focused on the win.",
    "{A} stares at the elimination wall like it’s calling their name.",
    "{A} keeps it cute in public, but their confessional energy is spicy.",
    "{A} makes a playlist called “Banishment Energy” and blasts it.",
    "{A} sits with a blanket and watches everyone like it’s a reunion special.",
    "{A} buys time in the gym corner, lifting and venting under their breath.",
    "{A} checks their suitcase like they’re ready for anything.",
    "{A} takes a nap mid-chaos and wakes up refreshed and petty.",
    "{A} tests the hot tub temperature and claims it as their zone.",
    "{A} quietly replaces their toiletries because someone used them again.",
    "{A} stays in the kitchen, snacking and listening to every conversation.",
    "{A} looks calm all day, which makes everyone more nervous.",
    "{A} starts the day cheerful, then instantly switches when someone walks in.",
    "{A} spends the evening writing down who owes them loyalty.",
    "{A} does a full outfit change just to make a point at dinner."
  ],

  // -----------------------------------------------------
  // EVENTS 2: Positive/Neutral/Negative (2 people: A & B)
  // -----------------------------------------------------
  events2: {
    positive: [
      "{A} and {B} squash their issues and actually build trust.",
      "{A} and {B} lock in a real deal that could run the house.",
      "{A} gives {B} honest advice, and {B} actually listens.",
      "{A} and {B} team up socially and suddenly look dangerous.",
      "{A} and {B} have a productive talk that clears the air.",
      "{A} wins {B} over with charm — it’s hard to hate them right now.",
      "{A} and {B} do a quick workout together and bond over competition.",
      "{A} and {B} promise to protect each other if either wins power.",
      "{A} and {B} swap notes on everyone’s alliances and it clicks perfectly.",
      "{A} and {B} laugh for once and the tension finally breaks.",
      "{A} and {B} agree to a truce that feels surprisingly real.",
      "{A} and {B} practice for the next challenge and hype each other up.",
      "{A} and {B} make a pact to never say each other’s name in voting.",
      "{A} and {B} coordinate outfits for a night out and look like a unit.",
      "{A} and {B} handle a misunderstanding maturely and move on fast.",
      "{A} and {B} share a heartfelt moment that softens both of them.",
      "{A} and {B} trade secrets and it turns into mutual loyalty.",
      "{A} and {B} set up numbers for tonight and it’s clean and smart.",
      "{A} and {B} calmly map out the vote and shut down messy rumors.",
      "{A} and {B} agree to split information so neither gets blindsided.",
      "{A} and {B} help each other get ready and keep it positive.",
      "{A} and {B} make peace over food and it actually works.",
      "{A} and {B} decide to target bigger threats instead of each other.",
      "{A} and {B} keep each other grounded when the house gets loud.",
      "{A} and {B} start an alliance handshake and everyone clocks it.",
      "{A} and {B} turn shade into jokes and end up cracking up.",
      "{A} and {B} promise not to jump into other people’s fights.",
      "{A} and {B} sit down privately and settle everything like adults.",
      "{A} and {B} team up to prank the house and it lands perfectly.",
      "{A} and {B} agree on a long-term plan and stick to it for once.",
      "{A} and {B} share strategy openly and it makes both stronger.",
      "{A} and {B} protect each other in a group argument without escalating it.",
      "{A} and {B} work out a swap: safety now for loyalty later.",
      "{A} and {B} bond over past seasons and find common ground.",
      "{A} and {B} check in after a tense night and genuinely apologize.",
      "{A} and {B} start running the social scene like co-captains.",
      "{A} and {B} make a promise to keep it competition, not personal.",
      "{A} and {B} agree to take turns leading so neither gets targeted.",
      "{A} and {B} share a private laugh at the chaos and reset their vibe.",
      "{A} and {B} keep their alliance quiet and it’s working.",
      "{A} and {B} help each other study puzzle patterns for the final.",
      "{A} and {B} decide to vote the same way and stop splitting.",
      "{A} and {B} set boundaries and it makes their friendship stronger.",
      "{A} and {B} keep each other off the radar with smart conversations.",
      "{A} and {B} make peace in front of everyone and shock the house.",
      "{A} and {B} agree to take it easy on each other in confessionals.",
      "{A} and {B} trade small favors that build real trust.",
      "{A} and {B} walk outside and talk it out like it’s therapy.",
      "{A} and {B} toast to making it to the end and mean it.",
      "{A} and {B} quietly celebrate a win together and keep it classy."
    ],
    neutral: [
      "{A} and {B} have a conversation that stays friendly but guarded.",
      "{A} and {B} trade information without committing to anything.",
      "{A} and {B} keep it polite, but neither is fully buying it.",
      "{A} checks in with {B}, and the vibe is… cautious.",
      "{A} and {B} hang out briefly, then drift back to their own circles.",
      "{A} and {B} share a moment that could mean something later.",
      "{A} and {B} chat in the kitchen, but both keep their cards close.",
      "{A} and {B} make small talk while side-eyeing the rest of the house.",
      "{A} and {B} discuss the vote in vague terms and change the subject.",
      "{A} and {B} sit together at dinner, but it’s more strategic than friendly.",
      "{A} and {B} clear a minor misunderstanding without getting emotional.",
      "{A} and {B} agree to “see how it goes” and leave it there.",
      "{A} and {B} laugh at a joke, but the tension still lingers underneath.",
      "{A} and {B} exchange compliments that feel a little forced.",
      "{A} and {B} negotiate softly and avoid saying any names out loud.",
      "{A} and {B} check the temperature of the room before speaking.",
      "{A} and {B} share a cigarette break and talk around the real issue.",
      "{A} and {B} sit in the hot tub and keep it surface-level.",
      "{A} and {B} compare challenge strengths without making it personal.",
      "{A} and {B} agree the house is messy, but don’t add fuel to it.",
      "{A} and {B} talk about finals, then abruptly switch to gossip.",
      "{A} and {B} make a vague “we’re cool” statement and walk away.",
      "{A} and {B} exchange a quick apology and keep it moving.",
      "{A} and {B} try to be cordial in a group setting for appearances.",
      "{A} and {B} discuss who’s dangerous, but never name a target.",
      "{A} and {B} sit down, but both are clearly measuring each other.",
      "{A} and {B} set a soft boundary: no shouting, no extra drama today.",
      "{A} and {B} talk through a rumor, but neither fully trusts the answer.",
      "{A} and {B} agree to keep it competition-only… for now.",
      "{A} and {B} share a snack and pretend everything’s normal.",
      "{A} and {B} talk about their seasons and keep it respectful.",
      "{A} and {B} do a quick debrief after the challenge without any heat.",
      "{A} and {B} keep it short because the cameras feel too close.",
      "{A} and {B} exchange looks that say more than the words do.",
      "{A} and {B} apologize for tone, not for what they said.",
      "{A} and {B} make peace in public but avoid a private talk.",
      "{A} and {B} agree to not escalate if someone else starts something.",
      "{A} and {B} sit by the pool and let silence do the talking.",
      "{A} and {B} talk strategy, then separate before anyone notices.",
      "{A} and {B} share a joke and keep the rest strictly business.",
      "{A} and {B} plan a conversation for later and never follow up.",
      "{A} and {B} keep it respectful, but there’s no real warmth.",
      "{A} and {B} nod along to each other’s points and leave it unresolved.",
      "{A} and {B} talk about nomination scenarios without picking sides.",
      "{A} and {B} agree the house is watching, so they keep it quiet.",
      "{A} and {B} avoid eye contact, then finally say hello like adults.",
      "{A} and {B} compare notes, but both edit the truth a little.",
      "{A} and {B} sit close at the club night, but it’s strategic positioning.",
      "{A} and {B} end the conversation with “we’ll see,” and nothing changes.",
      "{A} and {B} keep it cute in the house and vent separately in confessionals."
    ],
    negative: [
      "{A} and {B} get into it and the house immediately picks sides.",
      "{A} calls {B} out, and {B} snaps right back.",
      "{A} tries to press {B}, but it turns into a full argument.",
      "{A} and {B} clash hard, and it feels personal.",
      "{A} says something slick to {B}, and {B} does not let it slide.",
      "{A} and {B} exchange words that definitely won’t be forgotten.",
      "{A} gets in {B}’s face and the whole room goes silent.",
      "{B} throws shade at {A} and it instantly escalates.",
      "{A} and {B} scream over each other until security steps closer.",
      "{A} splashes a drink near {B} and chaos erupts.",
      "{A} knocks over a chair while arguing with {B}.",
      "{A} and {B} start shoving and people rush to separate them.",
      "{A} drags {B} in front of everyone and refuses to stop.",
      "{B} calls {A} fake and {A} explodes on the spot.",
      "{A} and {B} argue over the vote and it turns into a personal attack.",
      "{A} accuses {B} of sneaking around and {B} laughs in their face.",
      "{A} and {B} go back-and-forth so long the house meeting collapses.",
      "{A} yells at {B} for touching their stuff and the tension spikes.",
      "{A} catches {B} talking about them and storms over immediately.",
      "{A} and {B} start banging on doors, demanding answers.",
      "{A} threatens to “handle it” and {B} dares them to try.",
      "{A} and {B} argue in the kitchen and plates start getting moved around.",
      "{A} calls {B} out for playing both sides, and {B} denies everything.",
      "{A} and {B} turn a joke into a fight in under ten seconds.",
      "{A} throws someone’s makeup bag toward {B} and the room erupts.",
      "{A} steps to {B} and people pull them back before it gets worse.",
      "{B} laughs while {A} is mad, and {A} loses it even more.",
      "{A} and {B} get so loud production has to pause the moment.",
      "{A} accuses {B} of lying on camera and {B} claps back.",
      "{A} and {B} argue in the hot tub and water goes everywhere.",
      "{A} tells {B} “say it again,” and the air gets dangerous.",
      "{A} and {B} exchange insults that cut way too deep.",
      "{A} calls {B} a follower and {B} calls {A} a bully.",
      "{A} drags {B}’s past season and {B} drags theirs right back.",
      "{A} and {B} go nose-to-nose and security separates them.",
      "{A} pushes {B}’s stuff aside like it’s trash and {B} snaps.",
      "{A} and {B} almost swing but get restrained at the last second.",
      "{A} throws a pillow at {B}, and it turns into a full screaming match.",
      "{A} slams a door after {B} and keeps yelling through it.",
      "{A} and {B} beef over the bedroom and it becomes territorial.",
      "{A} calls {B} disloyal and {B} exposes their whole plan.",
      "{A} and {B} fight over who started it, and nobody cares anymore.",
      "{A} calls {B} a snake, and {B} says they’ll prove it in battle.",
      "{A} and {B} argue so hard people start recording reactions.",
      "{A} throws shade at {B}’s performance and {B} snaps immediately.",
      "{A} and {B} get into a slap-box moment before it’s broken up.",
      "{A} and {B} argue at pregame and the night out turns ugly.",
      "{A} corners {B} for answers and {B} refuses to give them.",
      "{A} and {B} turn the living room into a reunion-level blowup.",
      "{A} and {B} go at it in the hallway and the whole house hears it."
    ]
  },

  // ----------------------------------------------------
  // EVENTS 3: Neutral/Positive (3 people: A, B, and C)
  // ----------------------------------------------------
  events3: {
    neutral: [
      "{A}, {B}, and {C} sit together and quietly compare notes.",
      "{A}, {B}, and {C} talk game, but no one fully shows their cards.",
      "{A}, {B}, and {C} have a group chat that feels… strategic.",
      "{A}, {B}, and {C} hang out, and the rest of the house watches closely.",
      "{A}, {B}, and {C} discuss tonight’s vote like it’s already decided.",
      "{A}, {B}, and {C} have a calm conversation that could shift numbers later.",
      "{A}, {B}, and {C} debrief the challenge and disagree politely on what happened.",
      "{A}, {B}, and {C} sit in the kitchen and trade house gossip carefully.",
      "{A}, {B}, and {C} try to mediate a situation before it blows up again.",
      "{A}, {B}, and {C} share a ride and keep the conversation strategic.",
      "{A}, {B}, and {C} talk in circles, making sure cameras don’t catch details.",
      "{A}, {B}, and {C} agree the house is tense and decide to lay low tonight.",
      "{A}, {B}, and {C} compare who they trust and who they don’t—quietly.",
      "{A}, {B}, and {C} have a house-meeting vibe, but nobody wants to lead it.",
      "{A}, {B}, and {C} talk about finals and what it’ll take to win.",
      "{A}, {B}, and {C} sit on the couch like judges and watch drama unfold.",
      "{A}, {B}, and {C} exchange side-eyes when a name gets mentioned nearby.",
      "{A}, {B}, and {C} talk about who’s overreacting, but keep it neutral.",
      "{A}, {B}, and {C} share snacks and act friendly while thinking strategically.",
      "{A}, {B}, and {C} sit outside and let the silence speak for them.",
      "{A}, {B}, and {C} trade information, but everyone edits the truth a little.",
      "{A}, {B}, and {C} agree to keep their distance from the loudest people tonight.",
      "{A}, {B}, and {C} discuss nominations without locking anything in.",
      "{A}, {B}, and {C} plan a conversation for later and then avoid it.",
      "{A}, {B}, and {C} compare who’s been doing too much in confessionals.",
      "{A}, {B}, and {C} watch a minor argument and choose not to jump in.",
      "{A}, {B}, and {C} try to clear the air after last night’s chaos.",
      "{A}, {B}, and {C} sit together at dinner, but the vibes are cautious.",
      "{A}, {B}, and {C} talk about “house rules” like they’re actually enforceable.",
      "{A}, {B}, and {C} discuss who would be scary in a Battle challenge.",
      "{A}, {B}, and {C} agree that the vote is messy, and leave it at that.",
      "{A}, {B}, and {C} trade stories from past seasons and keep it respectful.",
      "{A}, {B}, and {C} map out potential targets, but nobody says it clearly.",
      "{A}, {B}, and {C} meet in the hallway and talk in short, coded phrases.",
      "{A}, {B}, and {C} sit in glam and talk while getting ready for the night.",
      "{A}, {B}, and {C} share a laugh, but it doesn’t change the game.",
      "{A}, {B}, and {C} test each other with questions and watch the reactions.",
      "{A}, {B}, and {C} agree to keep it competition and stop making it personal.",
      "{A}, {B}, and {C} discuss who started the drama without taking sides.",
      "{A}, {B}, and {C} talk about loyalty and everyone defines it differently.",
      "{A}, {B}, and {C} check the vibe before walking into the main room.",
      "{A}, {B}, and {C} start to strategize, then stop when someone walks in.",
      "{A}, {B}, and {C} compare notes on who’s training the hardest.",
      "{A}, {B}, and {C} talk about the club night and who embarrassed themselves.",
      "{A}, {B}, and {C} sit by the pool and keep it surface-level for once.",
      "{A}, {B}, and {C} agree to let tonight play out and regroup after.",
      "{A}, {B}, and {C} talk about respect in the house, but nobody budges.",
      "{A}, {B}, and {C} share a quiet moment before the vote gets announced.",
      "{A}, {B}, and {C} compare who they think is bluffing and who isn’t.",
      "{A}, {B}, and {C} sit together and watch the house like it’s a reunion stage."
    ],
    positive: [
      "{A}, {B}, and {C} solidify a trio — and it suddenly feels powerful.",
      "{A}, {B}, and {C} agree on a plan and it actually makes sense.",
      "{A}, {B}, and {C} bond unexpectedly, and it boosts all their confidence.",
      "{A}, {B}, and {C} openly back each other and it changes the vibe in the house.",
      "{A}, {B}, and {C} coordinate perfectly and look like a real unit.",
      "{A}, {B}, and {C} form a pact that could carry them deep into the game.",
      "{A}, {B}, and {C} lock in numbers and shut down a blindside attempt.",
      "{A}, {B}, and {C} agree to protect each other through nominations.",
      "{A}, {B}, and {C} share intel and it makes their strategy airtight.",
      "{A}, {B}, and {C} decide to target bigger threats and stay unified.",
      "{A}, {B}, and {C} handle conflict maturely and come out stronger.",
      "{A}, {B}, and {C} create a voting plan that’s clean and hard to break.",
      "{A}, {B}, and {C} keep each other calm when the house gets chaotic.",
      "{A}, {B}, and {C} have a real heart-to-heart and the bond feels genuine.",
      "{A}, {B}, and {C} agree on boundaries and stop feeding pointless drama.",
      "{A}, {B}, and {C} quietly run the social scene like a power triangle.",
      "{A}, {B}, and {C} stick together at the club and control the night.",
      "{A}, {B}, and {C} make a pact: no turning on each other, period.",
      "{A}, {B}, and {C} plan out the endgame and it’s scary how solid it is.",
      "{A}, {B}, and {C} decide to train together and push each other hard.",
      "{A}, {B}, and {C} back each other in a house meeting and win respect.",
      "{A}, {B}, and {C} settle a rumor by talking it out and staying united.",
      "{A}, {B}, and {C} call out messy gameplay and keep the focus on winning.",
      "{A}, {B}, and {C} coordinate stories so nobody can twist the narrative.",
      "{A}, {B}, and {C} make a promise to keep it real, not fake for cameras.",
      "{A}, {B}, and {C} form a secret handshake and the alliance is official.",
      "{A}, {B}, and {C} agree to split duties: social, strategy, and training.",
      "{A}, {B}, and {C} keep each other off the radar with smart positioning.",
      "{A}, {B}, and {C} protect a member of the trio from being nominated.",
      "{A}, {B}, and {C} plan a clean flip and execute it without drama.",
      "{A}, {B}, and {C} decide to stop reacting and start controlling outcomes.",
      "{A}, {B}, and {C} give each other pep talks like it’s the final already.",
      "{A}, {B}, and {C} manage to turn enemies into distractions for everyone else.",
      "{A}, {B}, and {C} agree to vote as one, no matter what pressure comes.",
      "{A}, {B}, and {C} make peace with someone outside the trio—together.",
      "{A}, {B}, and {C} keep their pact quiet and it’s paying off.",
      "{A}, {B}, and {C} decide to play clean and still dominate strategically.",
      "{A}, {B}, and {C} celebrate a small win and strengthen their loyalty.",
      "{A}, {B}, and {C} calmly shut down a confrontation before it escalates.",
      "{A}, {B}, and {C} set a trap for a snake and it works perfectly.",
      "{A}, {B}, and {C} agree to share power instead of fighting over it.",
      "{A}, {B}, and {C} align on a target and nobody can shake them.",
      "{A}, {B}, and {C} stand together in the main room and the house notices.",
      "{A}, {B}, and {C} lock in final-four talk and it feels very real.",
      "{A}, {B}, and {C} promise to keep it sisterhood… and competition.",
      "{A}, {B}, and {C} read the room perfectly and adjust their plan instantly.",
      "{A}, {B}, and {C} decide to stop giving energy to drama and focus on wins.",
      "{A}, {B}, and {C} help each other calm down after a tense night out.",
      "{A}, {B}, and {C} coordinate a vote split to protect themselves.",
      "{A}, {B}, and {C} lock eyes and silently agree: they’re taking this season."
    ]
  }
};
